query openconfig_leaf_config($device: String!) {
  DcimDevice(name__value: $device) {
    edges {
      node {
        id
        name {
          value
        }
        interfaces {
          edges {
            node {
              name {
                value
              }
              description {
                value
              }
              status {
                value
              }
              ... on InterfacePhysical {
                mtu {
                  value
                }
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                    }
                  }
                }
              }
              ... on InterfaceVirtual {
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
