---
version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "pytest"
        update-types: ["version-update:semver-major"]
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns:
          - "*"
# yamllint disable rule:truthy
# version: 2

# updates:
#   # Maintain dependencies for GitHub Actions
#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#       time: "09:00"
#     target-branch: main
#     labels:
#       - "patch"
#     groups:
#       all:
#         patterns:
#           - "*"

#   # Group all pip updates except infrahub-sdk
#   - package-ecosystem: "uv"
#     directory: "/"
#     schedule:
#       interval: "daily"
#       time: "12:00"
#     open-pull-requests-limit: 10
#     labels:
#       - "patch"
#     # groups:
#     #   all:
#     #     patterns:
#     #       - "^(?!infrahub-sdk$).*"  # Regex to exclude infrahub-sdk
#     #   infrahub-sdk:
#     #     patterns:
#     #       - "infrahub-sdk"