---
jinja2_transforms:
  # Cisco
  - name: "cisco_pop_router"
    description: "Template to generate startup configuration for a cisco POP router"
    query: "pop_config"
    template_path: "templates/configs/cisco_pop_router.j2"
  - name: "cisco_dc_leaf"
    description: "Template to generate startup configuration for a cisco DC leaf"
    query: "dc_leaf_config"
    template_path: "templates/configs/cisco_dc_leaf.j2"
  - name: "cisco_dc_spine"
    description: "Template to generate startup configuration for a cisco DC spine"
    query: "dc_spine_config"
    template_path: "templates/configs/cisco_dc_spine.j2"
  - name: "cisco_dc_oob"
    description: "Template to generate startup configuration for a cisco DC OOB"
    query: "dc_oob_config"
    template_path: "templates/configs/cisco_dc_oob.j2"
  # Juniper
  - name: "juniper_firewall"
    description: "Template to generate startup configuration for a Juniper SRX Firewall"
    query: "firewall_config"
    template_path: "templates/configs/juniper_srx.j2"
  # Arista
  - name: "arista_pop_router"
    description: "Template to generate startup configuration for a arista POP router"
    query: "pop_config"
    template_path: "templates/configs/arista_pop_router.j2"
  - name: "arista_dc_leaf"
    description: "Template to generate startup configuration for a arista DC leaf"
    query: "dc_leaf_config"
    template_path: "templates/configs/arista_dc_leaf.j2"
  - name: "arista_dc_spine"
    description: "Template to generate startup configuration for a arista DC spine"
    query: "dc_spine_config"
    template_path: "templates/configs/arista_dc_spine.j2"
  # Perle
  - name: "perle_dc_console"
    description: "Template to generate startup configuration for a perle DC console"
    query: "dc_console_config"
    template_path: "templates/configs/perle_dc_console.j2"
  # Containerlab
  - name: "topology_clab"
    description: "Template to generate a containerlab topology"
    query: "topology_simulator"
    template_path: "templates/simulators/clab_topology.j2"

artifact_definitions:
  # Cisco
  - name: "Cisco POP config"
    artifact_name: "cisco-pop-router"
    content_type: "text/plain"
    targets: "cisco_pop_router"
    transformation: "cisco_pop_router"
    parameters:
      device: "name__value"
  - name: "Cisco DC leaf config"
    artifact_name: "cisco-dc-leaf-config"
    content_type: "text/plain"
    targets: "dc_leaf_config"
    transformation: "dc_leaf_config"
    parameters:
      device: "name__value"
  - name: "Cisco DC spine config"
    artifact_name: "cisco-dc-spine-config"
    content_type: "text/plain"
    targets: "dc_spine_config"
    transformation: "dc_spine_config"
    parameters:
      device: "name__value"
  - name: "Cisco DC OOB config"
    artifact_name: "cisco-dc-oob-config"
    content_type: "text/plain"
    targets: "dc_oob_config"
    transformation: "dc_oob_config"
    parameters:
      device: "name__value"      
  # Arista
  - name: "Arista POP config"
    artifact_name: "arista-pop-router"
    content_type: "text/plain"
    targets: "arista_pop_router"
    transformation: "arista_pop_router"
    parameters:
      device: "name__value"
  - name: "Arista DC leaf config"
    artifact_name: "arista-dc-leaf-config"
    content_type: "text/plain"
    targets: "dc_leaf_config"
    transformation: "dc_leaf_config"
    parameters:
      device: "name__value"
  - name: "Arista DC spine config"
    artifact_name: "arista-dc-spine-config"
    content_type: "text/plain"
    targets: "dc_spine_config"
    transformation: "dc_spine_config"
    parameters:
      device: "name__value"
  # Juniper
  - name: "Juniper firewall config"
    artifact_name: "juniper-firewall-config"
    content_type: "text/plain"
    targets: "juniper_firewall"
    transformation: "juniper_firewall"
    parameters:
      device: "name__value"  
  # Perle
  - name: "Perle DC console config"
    artifact_name: "perle-dc-console-config"
    content_type: "text/plain"
    targets: "dc_console_config"
    transformation: "dc_console_config"
    parameters:
      device: "name__value"
  # Containerlab    
  - name: "Containerlab Topology"
    artifact_name: "containerlab-topology"
    content_type: "text/plain"
    targets: "topologies_clab"
    transformation: "topology_clab"
    parameters:
      topology_name: "name__value"

check_definitions:
  - name: validate_firewall
    class_name: InfrahubValidateFirewall
    file_path: "checks/validate_firewall.py"
    targets: "firewalls"
    parameters:
      device: "name__value"

generator_definitions:
  - name: create_dc
    file_path: "generators/generate_dc.py"
    targets: topologies_dc
    query: topology_dc
    class_name: DCTopologyGenerator
    parameters:
      name: "name__value"

queries:
  - name: topology_dc
    file_path: "queries/topology_dc.gql"
  - name: topology_pop
    file_path: "queries/topology_pop.gql"    
  - name: topology_simulator
    file_path: "queries/topology_clab.gql"
  - name: firewall_config
    file_path: "queries/firewall_config.gql"
  - name: pop_config
    file_path: "queries/pop_config.gql"
  - name: dc_leaf_config
    file_path: "queries/dc_leaf_config.gql"
  - name: dc_spine_config
    file_path: "queries/dc_spine_config.gql"
  - name: dc_oob_config
    file_path: "queries/dc_oob_config.gql"
  - name: dc_console_config
    file_path: "queries/dc_console_config.gql"  