---
jinja2_transforms:
  # Containerlab
  - name: topology_clab
    description: Template to generate a containerlab topology
    query: topology_simulator
    template_path: templates/clab_topology.j2

artifact_definitions:
  # Cisco
  - name: edge_config
    artifact_name: edge
    content_type: text/plain
    targets: edges
    transformation: edge
    parameters:
      device: name__value
  - name: leaf_config
    artifact_name: leaf
    content_type: text/plain
    targets: leafs
    transformation: leaf
    parameters:
      device: name__value
  - name: borderleaf_config
    artifact_name: border-leaf
    content_type: text/plain
    targets: border_leafs
    transformation: leaf
    parameters:
      device: name__value
  - name: spine_config
    artifact_name: spine
    content_type: text/plain
    targets: spines
    transformation: spine
    parameters:
      device: name__value
  - name: loadbalancer_config
    artifact_name: loadbalancer
    content_type: text/plain
    targets: loadbalancers
    transformation: loadbalancer
    parameters:
      device: name__value
  # Containerlab
  - name: Containerlab Topology
    artifact_name: containerlab-topology
    content_type: text/plain
    targets: topologies_clab
    transformation: topology_clab
    parameters:
      name: name__value

  - name: Cable matrix for Topology
    artifact_name: topology-cabling
    content_type: text/plain
    targets: topologies_dc
    transformation: topology_cabling
    parameters:
      name: name__value

  # Equinix POP
  - name: equinix_pop_config
    artifact_name: equinix_pop
    content_type: text/plain
    targets: equinix_pop
    transformation: equinix_pop
    parameters:
      name: name__value

check_definitions:
  - name: validate_spine
    class_name: CheckSpine
    file_path: checks/spine.py
    targets: spines
    parameters:
      device: name__value
  - name: validate_leaf
    class_name: CheckLeaf
    file_path: checks/leaf.py
    targets: leafs
    parameters:
      device: name__value
  - name: validate_edge
    class_name: CheckEdge
    file_path: checks/edge.py
    targets: edges
    parameters:
      device: name__value
  - name: validate_loadbalancer
    class_name: CheckLoadBalancer
    file_path: checks/loadbalancer.py
    targets: loadbalancers
    parameters:
      device: name__value

python_transforms:
  - name: topology_cabling
    class_name: TopologyCabling
    file_path: transforms/topology_cabling.py
  - name: leaf
    class_name: Leaf
    file_path: transforms/leaf.py
  - name: spine
    class_name: Spine
    file_path: transforms/spine.py
  - name: loadbalancer
    class_name: LoadBalancer
    file_path: transforms/loadbalancer.py
  - name: edge
    class_name: Edge
    file_path: transforms/edge.py
  - name: equinix_pop
    class_name: EquinixPOP
    file_path: transforms/equinix_pop.py

generator_definitions:
  - name: create_dc
    file_path: generators/generate_dc.py
    targets: topologies_dc
    query: topology_dc
    class_name: DCTopologyGenerator
    parameters:
      name: name__value
  - name: create_pop
    file_path: generators/generate_pop.py
    targets: topologies_pop
    query: topology_pop
    class_name: PopTopologyGenerator
    parameters:
      name: name__value

queries:
  - name: topology_dc
    file_path: queries/topology/dc.gql
  - name: topology_pop
    file_path: queries/topology/pop.gql
  - name: topology_simulator
    file_path: queries/topology/clab.gql
  - name: topology_cabling
    file_path: queries/topology/cabling.gql
  - name: leaf_config
    file_path: queries/config/leaf.gql
  - name: spine_config
    file_path: queries/config/spine.gql
  - name: edge_config
    file_path: queries/config/edge.gql
  - name: loadbalancer_config
    file_path: queries/config/loadbalancer.gql
  - name: loadbalancer_validation
    file_path: queries/validation/loadbalancer_validation.gql
  - name: oob_config
    file_path: queries/config/oob.gql
  - name: equinix_pop_config
    file_path: queries/config/equinix_pop.gql
# schemas:
#   - schemas/
# menus:
#   - menus/menu.yml
