---
jinja2_transforms:
  - name: "juniper_firewall_config"
    description: "Template to generate startup configuration for a Juniper SRX Firewall"
    query: "firewall_config"
    template_path: "templates/juniper_srx_config.j2"
  - name: "cisco_pop_router"
    description: "Template to generate startup configuration for a cisco POP router"
    query: "pop_config"
    template_path: "templates/cisco_pop_router.j2"
  - name: "arista_pop_router"
    description: "Template to generate startup configuration for a arista POP router"
    query: "pop_config"
    template_path: "templates/arista_pop_router.j2"
  - name: "topology_clab"
    query: "topology_simulator"
    template_path: "simulators/clab_topology.j2"

artifact_definitions:
  - name: "Juniper firewall config"
    artifact_name: "juniper-firewall-config"
    content_type: "text/plain"
    targets: "juniper_firewall"
    transformation: "juniper_firewall_config"
    parameters:
      device: "name__value"
  - name: "Cisco POP config"
    artifact_name: "cisco-pop-router"
    content_type: "text/plain"
    targets: "cisco_pop_router"
    transformation: "cisco_pop_router"
    parameters:
      device: "name__value"
  - name: "Containerlab Topology"
    artifact_name: "containerlab-topology"
    content_type: "text/plain"
    targets: "topologies_clab"
    transformation: "topology_clab"
    parameters:
      topology_name: "name__value"

check_definitions:
  - name: validate_firewall
    class_name: InfrahubValidateFirewall
    file_path: "checks/validate_firewall.py"
    targets: "firewalls"
    parameters:
      device: "name__value"

generator_definitions:
  - name: create_dc
    file_path: "generators/generate_dc.py"
    targets: topologies_dc
    query: topology_dc
    class_name: DCTopologyGenerator
    parameters:
      name: "name__value"

queries:
  - name: firewall_config
    file_path: "queries/firewall_config.gql"
  - name: pop_config
    file_path: "queries/pop_config.gql"
  - name: topology_dc
    file_path: "queries/topology_dc.gql"
  - name: topology_pop
    file_path: "queries/topology_pop.gql"    
  - name: topology_simulator
    file_path: "queries/topology_clab.gql"
