[project]
authors = [
    {name = "Tomek Zajac", email = "tomek@mastuazi.com"},
]
requires-python = "<3.13,>=3.9"
dependencies = [
    "invoke<3.0.0,>=2.2.0",
    "pytest<9.0.0,>=8.3.5",
    "infrahub-sdk[all]<2.0.0,>=1.7.2",
]
name = "infrahub-demo"
version = "0.1.0"
description = ""
readme = "README.md"

[dependency-groups]
dev = [
    "pytest<9.0.0,>=8.3.5",
    "ruff>=0.11.4",
]
