[project]
authors = [
    {name = "Tomek Zajac", email = "tomek@mastuazi.com"},
]
requires-python = "<3.13,>=3.9"
dependencies = [
    "invoke<3.0.0,>=2.2.0",
    "infrahub-sdk[all]>=1.7.2,<2.0.0",
]
name = "infrahub-demo"
version = "0.1.0"
description = "Design driven DC"
readme = "README.md"

[dependency-groups]
dev = [
    "pytest>=8.3.5,<9.0.0",
    "ruff>=0.11.4",
    "yamllint>=1.37.1",
]
