# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"

nodes:
  - name: CloudSecurityService
    namespace: Service
    menu_placement: ServiceGeneric
    include_in_menu: true
    icon: "mdi:cloud-lock-outline"
    description: "Cloud-based security service configuration"
    label: "Cloud Security Service"
    human_friendly_id:
      - "name__value"
    inherit_from:
      - ServiceGeneric
    attributes:
      - name: service_type
        kind: Dropdown
        description: "Type of cloud security service"
        order_weight: 100
        choices:
          - name: sase
            label: SASE (Secure Access Service Edge)
            description: "Comprehensive SASE platform"
            color: "#1976D2"
          - name: swg
            label: Secure Web Gateway
            description: "Web security gateway"
            color: "#388E3C"
          - name: casb
            label: Cloud Access Security Broker
            description: "Cloud application security"
            color: "#F57C00"
          - name: ztna
            label: Zero Trust Network Access
            description: "Zero trust access platform"
            color: "#7B1FA2"
          - name: dlp
            label: Data Loss Prevention
            description: "Cloud DLP service"
            color: "#C62828"
          - name: firewall
            label: Cloud Firewall
            description: "Cloud-based firewall service"
            color: "#D32F2F"
        default_value: "sase"
        optional: false
      - name: provider
        kind: Text
        optional: false
        description: "Service provider name (e.g., Zscaler, Prisma, Umbrella)"
        order_weight: 200
      - name: tenant_id
        kind: Text
        optional: false
        unique: true
        description: "Unique tenant/organization identifier"
        order_weight: 300
      - name: api_endpoint
        kind: Text
        optional: false
        description: "API endpoint URL for management"
        order_weight: 400
      - name: cloud_region
        kind: Text
        optional: true
        description: "Primary cloud region/instance"
        order_weight: 500
    relationships:
      - name: gateways
        peer: ServiceCloudGateway
        cardinality: many
        optional: true
        kind: Component
        description: "Cloud gateways/POPs for this service"
        order_weight: 600

  - name: CloudGateway
    namespace: Service
    menu_placement: ServiceGeneric
    include_in_menu: true
    icon: "mdi:router-wireless"
    description: "Cloud security gateway/point of presence"
    label: "Cloud Gateway"
    human_friendly_id:
      - "name__value"
    inherit_from:
      - ServiceGeneric
    attributes:
      - name: gateway_type
        kind: Dropdown
        description: "Type of cloud gateway"
        order_weight: 100
        choices:
          - name: pop
            label: Point of Presence
            description: "Cloud provider's point of presence"
            color: "#4CAF50"
          - name: tunnel
            label: IPSec Tunnel
            description: "IPSec tunnel endpoint"
            color: "#FF9800"
          - name: gre_tunnel
            label: GRE Tunnel
            description: "GRE tunnel endpoint"
            color: "#2196F3"
          - name: proxy
            label: Proxy Gateway
            description: "HTTP/HTTPS proxy endpoint"
            color: "#9C27B0"
          - name: dns
            label: DNS Gateway
            description: "DNS-based security gateway"
            color: "#607D8B"
        default_value: "pop"
        optional: false
      - name: city
        kind: Text
        optional: true
        order_weight: 200
      - name: country
        kind: Text
        optional: true
        order_weight: 300
      - name: latitude
        kind: Number
        optional: true
        order_weight: 400
      - name: longitude
        kind: Number
        optional: true
        order_weight: 500
      - name: capacity_mbps
        kind: Number
        optional: true
        description: "Gateway capacity in Mbps"
        order_weight: 600
      - name: endpoint_address
        kind: Text
        optional: true
        description: "Gateway endpoint IP or FQDN"
        order_weight: 700
    relationships:
      - name: service
        peer: ServiceCloudSecurityService
        cardinality: one
        optional: false
        kind: Attribute
        order_weight: 800
      - name: security_zone
        peer: SecurityZone
        cardinality: one
        optional: true
        kind: Attribute
        description: "Security zone this gateway serves"
        order_weight: 900

  - name: CloudSecurityPolicyGroup
    namespace: Service
    menu_placement: ServiceGeneric
    include_in_menu: true
    icon: "mdi:shield-check-outline"
    description: "Cloud security policy group configuration"
    label: "Cloud Security Policy Group"
    human_friendly_id:
      - "name__value"
    inherit_from:
      - ServiceDeviceGeneric
    attributes:
      - name: cloud_policy_category
        kind: Dropdown
        description: "Category of cloud security policy"
        order_weight: 150
        choices:
          - name: web_filtering
            label: Web Filtering
            description: "URL/content filtering policy"
            color: "#2196F3"
          - name: app_control
            label: Application Control
            description: "Application-based policy"
            color: "#4CAF50"
          - name: ssl_inspection
            label: SSL Inspection
            description: "SSL/TLS inspection policy"
            color: "#FF9800"
          - name: cloud_firewall
            label: Cloud Firewall
            description: "Cloud-based firewall rules"
            color: "#F44336"
        default_value: "web_filtering"
        optional: false
      - name: cloud_enforcement_level
        kind: Dropdown
        description: "Cloud-specific enforcement level"
        order_weight: 250
        choices:
          - name: strict
            label: Strict
            description: "Strict cloud enforcement"
            color: "#F44336"
          - name: balanced
            label: Balanced
            description: "Balanced enforcement"
            color: "#FF9800"
          - name: permissive
            label: Permissive
            description: "Permissive cloud enforcement"
            color: "#4CAF50"
        default_value: "balanced"
        optional: false
    relationships:
      - name: cloud_security_service
        peer: ServiceCloudSecurityService
        cardinality: one
        optional: false
        kind: Attribute
        description: "Associated cloud security service"
        order_weight: 350
      - name: source_gateways
        peer: ServiceCloudGateway
        cardinality: many
        optional: true
        kind: Attribute
        identifier: "cloud_policy__source_gateways"
        description: "Source cloud gateways"
        order_weight: 400
      - name: destination_gateways
        peer: ServiceCloudGateway
        cardinality: many
        optional: true
        kind: Attribute
        identifier: "cloud_policy__destination_gateways"
        description: "Destination cloud gateways"
        order_weight: 500

extensions:
  nodes:
    - kind: ServiceSecurityService
      relationships:
        - name: cloud_security_service
          peer: ServiceCloudSecurityService
          cardinality: one
          optional: true
          kind: Attribute
          description: "Associated cloud security service"
          order_weight: 800
        - name: cloud_policy_groups
          peer: ServiceCloudSecurityPolicyGroup
          cardinality: many
          optional: true
          kind: Attribute
          description: "Cloud security policy groups"
          order_weight: 900