---
# Security IP Addresses that reference IPAM IP Addresses
# NOTE: Load 01_ipam_for_security.yml FIRST to create the IPAM objects
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: SecurityIPAddress
  data:
    - name: "web-server-01"
      ipam_ip_address:
        data:
          address: "10.1.1.10/32"
      description: "Primary web server"

    - name: "web-server-02"
      ipam_ip_address:
        data:
          address: "10.1.1.11/32"
      description: "Secondary web server"

    - name: "db-server-01"
      ipam_ip_address:
        data:
          address: "10.1.2.10/32"
      description: "Primary database server"

    - name: "mail-server"
      ipam_ip_address:
        data:
          address: "10.1.1.20/32"
      description: "Mail server"

    - name: "dns-server-01"
      ipam_ip_address:
        data:
          address: "10.1.3.10/32"
      description: "Primary DNS server"

    - name: "ntp-server"
      ipam_ip_address:
        data:
          address: "10.1.3.20/32"
      description: "Network Time Protocol server"

---
# Security Prefixes that reference IPAM Prefixes
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: SecurityPrefix
  data:
    - name: "dmz-network"
      ipam_prefix:
        data:
          prefix: "10.1.1.0/24"
      description: "DMZ network segment"

    - name: "internal-network"
      ipam_prefix:
        data:
          prefix: "192.168.1.0/24"
      description: "Internal corporate network"

    - name: "guest-network"
      ipam_prefix:
        data:
          prefix: "172.16.1.0/24"
      description: "Guest network segment"

    - name: "management-network"
      ipam_prefix:
        data:
          prefix: "10.1.3.0/24"
      description: "Management network segment"

    - name: "server-network"
      ipam_prefix:
        data:
          prefix: "10.1.2.0/24"
      description: "Server network segment"

    - name: "internet"
      ipam_prefix:
        data:
          prefix: "0.0.0.0/0"
      description: "Any internet address"

---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: SecurityIPRange
  data:
    - name: "dhcp-pool-guest"
      start: "172.16.1.100"
      end: "172.16.1.200"
      description: "DHCP pool for guest network"

    - name: "dhcp-pool-internal"
      start: "192.168.1.100"
      end: "192.168.1.200"
      description: "DHCP pool for internal network"

---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: SecurityFQDN
  data:
    - name: "company-website"
      fqdn: "www.company.com"
      description: "Company public website"

    - name: "mail-server-fqdn"
      fqdn: "mail.company.com"
      description: "Company mail server"

    - name: "intranet-portal"
      fqdn: "intranet.company.local"
      description: "Internal company portal"
