---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: SecuritySchedule
  data:
    - name: "business-hours"
      description: "Standard business hours Monday-Friday"
      days_of_week: "monday,tuesday,wednesday,thursday,friday"
      start_time: "08:00"
      end_time: "18:00"
      timezone: "UTC"

    - name: "after-hours"
      description: "After business hours and weekends"
      days_of_week: "saturday,sunday"
      start_time: "00:00"
      end_time: "23:59"
      timezone: "UTC"

    - name: "maintenance-window"
      description: "Weekly maintenance window"
      days_of_week: "sunday"
      start_time: "02:00"
      end_time: "04:00"
      timezone: "UTC"

    - name: "peak-hours"
      description: "Peak business hours"
      days_of_week: "monday,tuesday,wednesday,thursday,friday"
      start_time: "09:00"
      end_time: "17:00"
      timezone: "UTC"

    - name: "lunch-break"
      description: "Lunch break period"
      days_of_week: "monday,tuesday,wednesday,thursday,friday"
      start_time: "12:00"
      end_time: "13:00"
      timezone: "UTC"

    - name: "extended-hours"
      description: "Extended business hours including weekends"
      days_of_week: "monday,tuesday,wednesday,thursday,friday,saturday"
      start_time: "07:00"
      end_time: "20:00"
      timezone: "UTC"

    - name: "night-shift"
      description: "Night shift hours"
      days_of_week: "monday,tuesday,wednesday,thursday,friday"
      start_time: "22:00"
      end_time: "06:00"
      timezone: "UTC"
