---
# Security Object Relationships
# This file creates many-to-many relationships between security objects
# Load this AFTER all other security object files (01-15)

apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: SecurityAddressGroup
  data:
    # web-servers group with IP addresses
    - name: "web-servers"
      ip_addresses: [["web-server-01"], ["web-server-02"]]

    # internet group with prefix
    - name: "internet"
      prefixes: [["internet"]]

---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: SecurityServiceGroup
  data:
    # web-services group with HTTPS service
    - name: "web-services"
      services: [["https"]]

---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: SecurityPolicy
  data:
    # corporate-firewall-policy with corp-firewall
    - name: "corporate-firewall-policy"
      firewalls: [["corp-firewall"]]

---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: SecurityPolicyRule
  data:
    # allow-web-traffic rule with all relationships
    - name: "allow-web-traffic"
      source_addresses: [["internet"]]
      destination_addresses: [["web-servers"]]
      services: [["web-services"]]
      applications: [["web-browsing"]]
