---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: TopologyDataCenter
  data:
    - name: dc-juniper
      location: London
      description: Juniper Data Center with Juniper QFX5220-32CD
      strategy: ospf-ibgp
      design: PHYSICAL DC JUNIPER S
      emulation: true
      provider: Technology Partner
      management_subnet:
        data:
          prefix: 172.20.10.0/24
          status: active
          role: management
      customer_subnet:
        data:
          prefix: 10.10.0.0/16
          status: active
          role: supernet
      technical_subnet:
        data:
          prefix: 1.10.0.0/24
          status: active
          role: loopback
      member_of_groups:
        - topologies_dc
        - topologies_clab
