# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"
generics:
  - name: Routing
    namespace: Service
    description: "Base service for all routing protocols that can be attached to devices."
    label: Network Routing Service
    icon: "carbon:network-4"
    include_in_menu: false
    # default_filter: device
    human_friendly_id:
      - "name__value"
    attributes:
      - name: name
        kind: Text
        description: "Name of the routing service"
        optional: false
        order_weight: 1100
      # - name: routing_domain
      #   state: absent
      #   kind: Text
      #   description: "Name of the routing domain this service belongs to"
      #   order_weight: 1200
      # - name: priority
      #   kind: Number
      #   description: "Priority of this routing service (higher number means higher priority)"
      #   default_value: 100
      #   order_weight: 1300
      # - name: routing_instance
      #   kind: Text
      #   description: "Name of the routing instance on the device"
      #   optional: true
      #   order_weight: 1400
    relationships:
      - name: device
        peer: DcimGenericDevice
        optional: false
        cardinality: one
        kind: Attribute
        identifier: device_service
        order_weight: 1000

nodes:
  - name: OSPF
    namespace: Service
    description: "OSPF routing service that can be attached to devices"
    label: OSPF Service
    icon: "carbon:network-4-reference"
    menu_placement: ServiceGeneric
    include_in_menu: false
    human_friendly_id:
      - "name__value"
    inherit_from:
      - ServiceDeviceGeneric
      - ServiceRouting
    attributes:
      - name: process_id
        kind: Text
        description: "OSPF process ID on the device"
        default_value: "1"
        order_weight: 1500
      - name: version
        kind: Dropdown
        choices:
          - name: ospf
            label: OSPFv2
            description: "Open Shortest Path First version 2."
            color: "#E6E6FA" # lavender
          - name: ospfv3
            label: OSPFv3
            description: "Open Shortest Path First version 3."
            color: "#ECD6FA" # lavender
      - name: router_type
        kind: Dropdown
        description: "Type of OSPF router"
        choices:
          - name: abr
            label: Area Border Router
            description: "Connects multiple OSPF areas"
          - name: asbr
            label: Autonomous System Border Router
            description: "Connects to external routing domains"
          - name: internal
            label: Internal Router
            description: "Router within a single OSPF area"
        default_value: "internal"
        order_weight: 1600
      - name: reference_bandwidth
        kind: Number
        description: "Reference bandwidth for OSPF cost calculation (Mbps)"
        default_value: 100000
        optional: true
        order_weight: 1700
    relationships:
      - name: router_id
        peer: IpamIPAddress
        optional: false
        cardinality: one
        kind: Attribute
        order_weight: 1500
      - name: area
        peer: RoutingOSPFArea
        optional: false
        cardinality: one
        kind: Attribute
        order_weight: 1600
      - name: ospf_interface
        peer: DcimInterface
        label: Interface
        cardinality: many
        kind: Component
        optional: true
        on_delete: no-action
        identifier: interface_service
      - name: ospf_interface_profile
        peer: RoutingOSPFInterface
        label: Routing OSPF Interface Profile
        cardinality: one
        kind: Generic
        optional: true
        on_delete: no-action

  - name: BGP
    namespace: Service
    description: "BGP routing service that can be attached to devices"
    label: BGP Service
    icon: "carbon:network-4-reference"
    menu_placement: ServiceGeneric
    include_in_menu: false
    inherit_from:
      - ServiceRouting
      - ServiceDeviceGeneric
    human_friendly_id:
      - "name__value"
    attributes:
      - name: session_type
        kind: Dropdown
        description: "Type of BGP session"
        choices:
          - name: INTERNAL
            label: iBGP
            description: "Internal BGP session within the same AS"
          - name: EXTERNAL
            label: eBGP
            description: "External BGP session between different ASs"
        order_weight: 1500
      - name: multipath
        kind: Boolean
        description: "Whether BGP multipath is enabled"
        default_value: false
        optional: true
        order_weight: 1600
      - name: graceful_restart
        kind: Boolean
        description: "Whether graceful restart is enabled"
        default_value: true
        optional: true
        order_weight: 1700
    relationships:
      - name: router_id
        peer: IpamIPAddress
        optional: false
        cardinality: one
        kind: Attribute
        order_weight: 1500
        identifier: bgp_router_id
      - name: local_as
        peer: RoutingAutonomousSystem
        optional: false
        cardinality: one
        kind: Attribute
        order_weight: 1600
        identifier: bgp_local_as
      - name: remote_as
        peer: RoutingAutonomousSystem
        optional: false
        cardinality: one
        kind: Attribute
        order_weight: 1700
        identifier: bgp_remote_as
      - name: local_ip
        peer: IpamIPAddress
        optional: false
        cardinality: one
        kind: Attribute
        order_weight: 1800
        identifier: bgp_local_ip
      - name: remote_ip
        peer: IpamIPAddress
        optional: false
        cardinality: one
        kind: Attribute
        order_weight: 1900
        identifier: bgp_remote_ip
      - name: peer_group
        peer: RoutingBGPPeerGroup
        optional: true
        cardinality: one
        kind: Attribute
        order_weight: 2000

extensions:
  nodes:
    - kind: RoutingOSPFInterface
      relationships:
        - name: ospf_services
          label: OSPF Services
          kind: Component
          cardinality: many
          optional: true
          peer: ServiceOSPF
          order_weight: 2000
