# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"
generics:
  - name: Generic
    namespace: Service
    description: "Services"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        label: Name
        optional: false
        order_weight: 1
        description: Service Name
      - name: status
        order_weight: 30
        optional: false
        kind: Dropdown
        choices:
          - name: provisioning
            label: Provisioning
            description: "In the process of being set up and configured."
            color: "#ffff7f"
          - name: active
            label: Active
            description: "Fully operational and currently in service."
            color: "#7fbf7f"
          - name: decommissioning
            label: Decommissioning
            description: "In the process of beeing taken out of service."
            color: "#fbfbfb"
          - name: decommissioned
            label: Decommissioned
            description: "Taken out of service."
            color: "#bfbfbf"
    relationships:
      - name: owner
        peer: OrganizationGeneric
        cardinality: one
        kind: Component
        order_weight: 100
        optional: true
        on_delete: no-action

  # - name: InterfaceGeneric
  #   namespace: Service
  #   description: "Services"
  #   state: absent
  #   include_in_menu: false
  #   # This is only owning relationships toward various services for interfaces
  #   relationships:
  #     - name: network_segments
  #       label: Segments
  #       peer: ServiceNetworkSegment
  #       state: absent
  #       cardinality: many
  #       optional: true
  #       identifier: interface_services

extensions:
  nodes:
    - kind: DcimGenericDevice
      relationships:
        - name: device_service # l3_gateway
          peer: ServiceGeneric
          label: Services
          optional: true
          cardinality: many
          kind: Component
          # order_weight: 1400
          on_delete: no-action
          identifier: device_service
    # - kind: DcimInterface
    #   relationships:
    #     - name: services # l2_segment
    #       peer: ServiceInterfaceGeneric
    #       state: absent
    #       label: Interface Services # L2 Segment(s)
    #       identifier: interface_services
    #       optional: true
    #       cardinality: many
    #       kind: Generic
    #       # order_weight: 1400
    #       on_delete: no-action
    #       read_only: true
    # - kind: TopologyDeployment
    #   relationships:
    #     - name: fabric_services
    #       peer: ServiceGeneric
    #       label: Fabric Services
    #       optional: true
    #       cardinality: many
    #       kind: Component
    #       on_delete: no-action

    - kind: OrganizationProvider
      relationships:
        - name: asns
          label: ASNs
          peer: RoutingAutonomousSystem
          optional: true
          cardinality: many
          kind: Component
