# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"
generics:
  - name: Generic
    namespace: Service
    description: "Services"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        label: Name
        optional: false
        order_weight: 1
      - name: description
        kind: Text
        order_weight: 2
        optional: true
      - name: status
        order_weight: 3
        optional: false
        kind: Dropdown
        choices:
          - name: provisioning
            label: Provisioning
            description: "In the process of being set up and configured."
            color: "#ffff7f"
          - name: active
            label: Active
            description: "Fully operational and currently in service."
            color: "#7fbf7f"
          - name: decommissioning
            label: Decommissioning
            description: "In the process of beeing taken out of service."
            color: "#fbfbfb"
          - name: decommissioned
            label: Decommissioned
            description: "Taken out of service."
            color: "#bfbfbf"
    relationships:
      - name: owner
        peer: OrganizationGeneric
        cardinality: one
        kind: Component
        order_weight: 2000
        optional: true

nodes:
  # - name: BackBone
  #   namespace: Service
  #   label: "Backbone Service"
  #   description: "Backbone service attached to a Topology."
  #   icon: "carbon:container-services"
  #   menu_placement: ServiceGeneric
  #   inherit_from:
  #     - ServiceGeneric
  #   uniqueness_constraints:
  #     - ["circuit_id__value", "internal_circuit_id__value"]
  #   attributes:
  #     - name: circuit_id
  #       kind: Text
  #       label: Circuit ID
  #       optional: false
  #       order_weight: 3
  #     - name: internal_circuit_id
  #       kind: Text
  #       label: Internal Circuit ID
  #       optional: false
  #       order_weight: 2
  #   relationships:
  #     - name: provider
  #       cardinality: one
  #       peer: OrganizationProvider
  #       optional: false
  #       kind: Attribute
  #     - name: site_a
  #       label: Site A
  #       cardinality: one
  #       peer: LocationMetro
  #       optional: false
  #       identifier: infrabackboneservice__location_site_a
  #       kind: Attribute
  #       order_weight: 4
  #     - name: site_b
  #       label: Site B
  #       cardinality: one
  #       peer: LocationMetro
  #       optional: false
  #       identifier: infrabackboneservice__location_site_b
  #       kind: Attribute
  #       order_weight: 5

  - name: Layer2Network
    namespace: Service
    description: "Layer 2 network service attached to a Topology."
    label: Layer2 Network Segment
    icon: "carbon:ibm-cloud-internet-services"
    menu_placement: ServiceGeneric
    inherit_from:
      - ServiceGeneric
    attributes:
      - name: vlan
        label: VLAN assignment
        order_weight: 10
        optional: false
        kind: Number
    relationships:
      - name: interfaces
        peer: DcimInterface
        label: Interfaces
        cardinality: many
        kind: Generic
        optional: true
        on_delete: no-action
        identifier: interface_service

  - name: Layer3Gateway
    namespace: Service
    description: "Layer 3 network service attached to a Topology."
    label: Layer3 Gateway
    icon: "carbon:ibm-cloud-internet-services"
    menu_placement: ServiceGeneric
    inherit_from:
      - ServiceGeneric
    attributes:
      - name: is_anycast
        kind: Boolean
        label: Anycast Gateway
        default_value: false
        optional: false
        order_weight: 10
    relationships:
      - name: prefix
        peer: IpamPrefix
        cardinality: one
        kind: Component
        order_weight: 1400
        optional: true
      - name: interfaces
        peer: DcimInterface
        label: Interfaces
        cardinality: many
        kind: Generic
        optional: true
        on_delete: no-action
        identifier: interface_service

extensions:
  # state: present
  nodes:
    - kind: DcimGenericDevice
      relationships:
        - name: device_service # l3_gateway
          # state: absent
          peer: ServiceGeneric
          label: Services
          optional: true
          cardinality: many
          kind: Attribute
          order_weight: 1400
          on_delete: no-action
          identifier: device_service
    - kind: DcimInterface
      relationships:
        - name: service # l2_segment
          peer: ServiceGeneric
          label: Interface Services # L2 Segment(s)
          identifier: interface_service
          # state: absent
          optional: true
          cardinality: many
          kind: Generic
          order_weight: 1400
          on_delete: no-action
          read_only: true
                    
    - kind: TopologyDeployment
      relationships:
        - name: fabric_services
          peer: ServiceGeneric
          label: Fabric Services
          optional: true
          cardinality: many
          kind: Component
          on_delete: no-action

    - kind: OrganizationProvider
      relationships:
        - name: asns
          label: ASNs
          peer: ServiceAutonomousSystem
          optional: true
          cardinality: many
          kind: Component
