# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"
nodes:
  - name: BGPFabricPeering
    state: absent
    namespace: Service
    description: "BGP Fabric Peering service attached to a Topology."
    label: BGP Fabric Peering
    icon: "carbon:ibm-cloud-internet-services"
    menu_placement: ServiceGeneric
    include_in_menu: false
    inherit_from:
      - ServiceGeneric
    relationships:
      - name: endpoints
        state: absent
        peer: DcimBGPPeeringEndpoint
        optional: true
        cardinality: many
        kind: Component
      - name: device
        peer: DcimGenericDevice
        optional: true
        cardinality: one
        kind: Attribute
        identifier: device_service

  - name: BGPPeeringEndpoint
    state: absent
    namespace: Dcim
    description: A peering endpoint
    label: Peering Endpoint
    icon: mdi:ethernet
    menu_placement: ServiceGeneric
    include_in_menu: false
    # human_friendly_id:
    #   - service__name__value
    #   - name__value
    uniqueness_constraints:
      - [service, name__value]
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        description: Name of the circuit endoint, could be a MMR position for instance.
        order_weight: 1000
      - name: status
        kind: Dropdown
        optional: true
        choices:
          - name: active
            label: Active
            description: Fully operational and currently in service.
            color: "#7fbf7f"
          - name: provisioning
            label: Provisioning
            description: In the process of being set up and configured.
            color: "#ffff7f"
          - name: maintenance
            label: Maintenance
            description: Undergoing routine maintenance or repairs.
            color: "#ffd27f"
          - name: drained
            label: Drained
            description: Temporarily taken out of service.
            color: "#bfbfbf"
      - name: description
        kind: Text
        optional: true
    relationships:
      - name: service
        state: absent
        peer: ServiceBGPFabricPeering
        order_weight: 900
        optional: false
        cardinality: one
        kind: Parent
      - name: bgp_sessions
        state: absent
        peer: RoutingBGPSession
        optional: true
        cardinality: many
        kind: Attribute
---
version: "1.0"
nodes:
  - name: OSPFFabricPeering
    state: absent
    namespace: Service
    description: "OSPF Fabric Peering service attached to a Topology."
    label: OSPF Fabric Peering
    icon: "carbon:ibm-cloud-internet-services"
    menu_placement: ServiceGeneric
    include_in_menu: false
    inherit_from:
      - ServiceGeneric
    relationships:
      - name: endpoints
        peer: DcimPeeringEndpoint
        optional: true
        cardinality: many
        kind: Component
      - name: ospf_sessions
        peer: RoutingOSPF
        optional: true
        cardinality: many
        kind: Component
      - name: device
        peer: DcimGenericDevice
        optional: true
        cardinality: one
        kind: Attribute
        identifier: device_service
