# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"
generics:
  - name: PolicyAssignment
    namespace: Security
    label: Security Policy
    include_in_menu: false
    relationships:
      - name: rules
        label: Policy
        peer: SecurityRenderedPolicyRule
        kind: Component
        cardinality: many
        optional: true
  - name: BasePolicyRule
    namespace: Security
    include_in_menu: false
    attributes:
      - name: index
        label: Index
        kind: Number
        optional: false
        order_weight: 99999
      - name: name
        label: Name
        kind: Text
        optional: false
      - name: action
        label: Action
        kind: Text
        enum: ["permit", "deny"]
        default_value: permit
        optional: false
      - name: log
        label: Log
        kind: Boolean
        default_value: false
        optional: true
        order_weight: 99998
  - name: GenericAddressGroup
    namespace: Security
    include_in_menu: false
    display_labels:
      - name__value
    hierarchical: true
    attributes:
      - name: name
        kind: Text
        label: Name
        optional: false
        unique: true
      - name: description
        label: Description
        kind: Text
        optional: true
    relationships:
      - name: addresses
        peer: SecurityGenericAddress
        cardinality: many
        kind: Component
        optional: true
  - name: GenericAddress
    namespace: Security
    display_labels:
      - name__value
    include_in_menu: false
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
    # Removed reverse relationship - use address_groups__addresses for queries
  - name: GenericServiceGroup
    namespace: Security
    include_in_menu: false
    hierarchical: true
    display_labels:
      - name__value
    attributes:
      - name: name
        label: Name
        kind: Text
        optional: false
      - name: description
        label: Description
        kind: Text
        optional: true
    relationships:
      - name: services
        peer: SecurityGenericService
        label: Services
        cardinality: many
        kind: Component
        optional: true
  - name: GenericService
    include_in_menu: false
    namespace: Security
    display_labels:
      - name__value
    attributes:
      - name: name
        label: Name
        kind: Text
        optional: false
      - name: description
        kind: Text
        label: Description
        optional: true
    # Removed reverse relationship - use service_groups__services for queries

nodes:
  - name: Zone
    namespace: Security
    menu_placement: SecurityPolicy
    human_friendly_id:
      - name__value
    display_labels:
      - name__value
    include_in_menu: true
    icon: "game-icons:fire-zone"
    description: "Security zones"
    label: "Security zone"
    attributes:
      - name: name
        kind: Text
        unique: true
        optional: false
      - name: trust_level
        kind: Number
        label: Trust Level
        optional: true
        description: "Security trust level (0-100, higher = more trusted)"
      - name: description
        kind: Text
        optional: true
      - name: parent_zone_name
        kind: Text
        optional: true
        label: Parent Zone
        description: "Name of parent zone (for organizational hierarchy)"

  - name: IpamIPAddress
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "mdi:ip-outline"
    description: "Infrahub IPv4/6 address"
    label: "IPAM IP Address"
    human_friendly_id:
      - name__value
    inherit_from:
      - SecurityGenericAddress
    attributes:
      - name: description
        kind: Text
        optional: true
    relationships:
      - name: ip_address
        peer: IpamIPAddress
        cardinality: one
        kind: Attribute
        optional: false
  - name: IpamPrefix
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "mdi:ip-network-outline"
    description: "Infrahub IPv4/6 prefix"
    label: "IPAM IP Prefix"
    human_friendly_id:
      - name__value
    inherit_from:
      - SecurityGenericAddress
    attributes:
      - name: description
        kind: Text
        optional: true
    relationships:
      - name: ip_prefix
        peer: IpamPrefix
        cardinality: one
        kind: Attribute
        optional: false
  - name: IPAddress
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    description: "IPv4/6 address"
    human_friendly_id:
      - name__value
    label: "IP Address"
    icon: "mdi:ip-outline"
    inherit_from:
      - SecurityGenericAddress
    order_by:
      - "address__value"
    display_labels:
      - name__value
      - address__value
    attributes:
      - name: address
        kind: IPHost
      - name: description
        kind: Text
        optional: true
  - name: Prefix
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "mdi:ip-network-outline"
    description: "IPv4/6 prefix"
    label: "Prefix"
    human_friendly_id:
      - name__value
    inherit_from:
      - "SecurityGenericAddress"
    order_by:
      - name__value
    display_labels:
      - name__value
      - prefix__value
    attributes:
      - name: prefix
        kind: IPNetwork
        optional: false
        unique: true
      - name: description
        kind: Text
        optional: true
  - name: IPRange
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "mdi:ip-outline"
    description: "IPv4/6 Range"
    label: "IP Range"
    human_friendly_id:
      - name__value
    display_labels:
      - name__value
    inherit_from:
      - "SecurityGenericAddress"
    order_by:
      - name__value
    attributes:
      - name: start
        label: Start IP Address
        kind: IPHost
        optional: false
      - name: end
        label: End IP Address
        kind: IPHost
        optional: false
      - name: description
        kind: Text
        optional: true
  - name: FQDN
    namespace: Security
    description: "Full Qualified Domain Name"
    include_in_menu: true
    icon: "eos-icons:dns"
    menu_placement: SecurityPolicy
    label: "FQDN"
    human_friendly_id:
      - name__value
    display_labels:
      - name__value
    inherit_from:
      - "SecurityGenericAddress"
    order_by:
      - name__value
      - fqdn__value
    attributes:
      - name: fqdn
        label: FQDN
        kind: Text
        optional: false
        # https://stackoverflow.com/questions/11809631/fully-qualified-domain-name-validation
        regex: "(?=^.{1,253}$)(^(((?!-)[a-zA-Z0-9-]{1,63}(?<!-))|((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\\.)+[a-zA-Z]{2,63})$)"
      - name: description
        kind: Text
        optional: true
  - name: AddressGroup
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "material-symbols:menu-book-outline-rounded"
    description: "Group of addresses"
    label: Address Group
    human_friendly_id:
      - name__value
    parent: SecurityAddressGroup
    display_labels:
      - name__value
    uniqueness_constraints:
      - [name__value]
    inherit_from:
      - SecurityGenericAddressGroup

  - name: Service
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "eos-icons:application-outlined"
    description: "Service"
    label: Service
    human_friendly_id:
      - name__value
    display_labels:
      - name__value
    order_by:
      - name__value
    inherit_from:
      - SecurityGenericService
    attributes:
      - name: port
        kind: Number
        optional: false
      - name: protocol
        kind: Text
        enum: ["tcp", "udp", "icmp", "any"]
        default_value: "tcp"
        optional: false
      - name: description
        kind: Text
        optional: true

  - name: ServiceRange
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "eos-icons:application-outlined"
    description: "Service range"
    label: Service range
    human_friendly_id:
      - name__value
    display_labels:
      - name__value
    order_by:
      - name__value
    inherit_from:
      - SecurityGenericService
    attributes:
      - name: start
        kind: Number
        optional: false
      - name: end
        kind: Number
        optional: false
      - name: protocol
        kind: Text
        enum: ["tcp", "udp", "icmp", "any"]
        default_value: "tcp"
        optional: false

  - name: ServiceGroup
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "material-symbols:menu-book-outline-rounded"
    label: Service group
    description: "Group of services"
    human_friendly_id:
      - name__value
    display_labels:
      - name__value
    order_by:
      - name__value
    inherit_from:
      - SecurityGenericServiceGroup
  - name: Policy
    namespace: Security
    label: "Security Policy"
    human_friendly_id:
      - name__value
    display_labels:
      - name__value
    order_by:
      - name__value
    uniqueness_constraints:
      - [name__value]
    attributes:
      - name: name
        label: Name
        kind: Text
        optional: false
      - name: description
        label: Description
        kind: Text
        optional: true
      - name: parent_policy_name
        kind: Text
        optional: true
        label: Parent Policy
        description: "Name of parent policy (for organizational hierarchy)"
    relationships:
      - name: rules
        peer: SecurityPolicyRule
        cardinality: many
        kind: Component
      - name: location_target
        peer: LocationGeneric
        cardinality: one
        optional: true
        kind: Attribute
      # - name: device_target
      #   peer: DcimFirewall
      #   cardinality: one
      #   optional: true
      #   kind: Attribute
  - name: PolicyRule
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "material-symbols:policy"
    label: Policy rule
    description: "Policy rule"
    order_by:
      - source_zone__name__value
      - destination_zone__name__value
      - index__value
    uniqueness_constraints:
      - [index__value, name__value, source_zone, destination_zone, policy]
    display_labels:
      - index__value
      - name__value
    inherit_from:
      - SecurityBasePolicyRule
    relationships:
      - name: policy
        peer: SecurityPolicy
        kind: Attribute
        cardinality: one
        optional: false
      - name: source_zone
        peer: SecurityZone
        kind: Attribute
        cardinality: one
        optional: false
        order_weight: 1
        identifier: policy_rule__source_zone
      - name: destination_zone
        peer: SecurityZone
        kind: Attribute
        cardinality: one
        optional: false
        order_weight: 2
        identifier: policy_rule__destination_zone
      # Consolidated source relationships
      - name: source_objects
        peer: SecurityGenericAddress
        optional: true
        kind: Attribute
        cardinality: many
        identifier: policy_rule__source_objects
      - name: source_object_groups
        peer: SecurityGenericAddressGroup
        optional: true
        kind: Attribute
        cardinality: many
        identifier: policy_rule__source_object_groups
      - name: destination_objects
        peer: SecurityGenericAddress
        optional: true
        kind: Attribute
        cardinality: many
        identifier: policy_rule__destination_objects
      - name: destination_object_groups
        peer: SecurityGenericAddressGroup
        optional: true
        kind: Attribute
        cardinality: many
        identifier: policy_rule__destination_object_groups
      # Consolidated service relationships
      - name: services
        peer: SecurityGenericService
        optional: true
        kind: Attribute
        cardinality: many
        identifier: policy_rule__services
      - name: service_groups
        peer: SecurityGenericServiceGroup
        optional: true
        kind: Attribute
        cardinality: many
        identifier: policy_rule__service_groups
      # Advanced security features
      - name: applications
        peer: SecurityApplication
        optional: true
        kind: Attribute
        cardinality: many
        identifier: policy_rule__applications
      - name: url_categories
        peer: SecurityURLCategory
        optional: true
        kind: Attribute
        cardinality: many
        identifier: policy_rule__url_categories
      - name: security_profile
        peer: SecuritySecurityProfile
        optional: true
        kind: Attribute
        cardinality: one
        identifier: policy_rule__security_profile
      - name: schedule
        peer: SecuritySchedule
        optional: true
        kind: Attribute
        cardinality: one
        identifier: policy_rule__schedule

  - name: RenderedPolicyRule
    namespace: Security
    include_in_menu: false
    label: Policy rule
    description: "Policy rule"
    order_by:
      - source_zone__name__value
      - destination_zone__name__value
      - index__value
    inherit_from:
      - SecurityBasePolicyRule
    relationships:
      - name: source_policy
        peer: SecurityPolicy
        kind: Attribute
        cardinality: one
        optional: false
      - name: source_zone
        peer: SecurityZone
        kind: Attribute
        cardinality: one
        optional: false
        identifier: rendered_policy_rule__source_zone
        order_weight: 1
      - name: destination_zone
        peer: SecurityZone
        kind: Attribute
        cardinality: one
        optional: false
        identifier: rendered_policy_rule__destination_zone
        order_weight: 2
      # Consolidated source relationships
      - name: source_objects
        peer: SecurityGenericAddress
        optional: true
        kind: Attribute
        cardinality: many
        identifier: rendered_policy_rule__source_objects
      - name: source_object_groups
        peer: SecurityGenericAddressGroup
        optional: true
        kind: Attribute
        cardinality: many
        identifier: rendered_policy_rule__source_object_groups
      - name: destination_objects
        peer: SecurityGenericAddress
        optional: true
        kind: Attribute
        cardinality: many
        identifier: rendered_policy_rule__destination_objects
      - name: destination_object_groups
        peer: SecurityGenericAddressGroup
        optional: true
        kind: Attribute
        cardinality: many
        identifier: rendered_policy_rule__destination_object_groups
      # Consolidated service relationships
      - name: services
        peer: SecurityGenericService
        optional: true
        kind: Attribute
        cardinality: many
        identifier: rendered_policy_rule__services
      - name: service_groups
        peer: SecurityGenericServiceGroup
        optional: true
        kind: Attribute
        cardinality: many
        identifier: rendered_policy_rule__service_groups

  - name: Application
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "mdi:application"
    description: "Security application definition"
    label: "Application"
    human_friendly_id:
      - name__value
    display_labels:
      - name__value
    inherit_from:
      - SecurityGenericService
    attributes:
      - name: category
        kind: Text
        optional: true
        label: Category
        description: "Application category (e.g., web-browsing, file-sharing)"
      - name: subcategory
        kind: Text
        optional: true
        label: Subcategory
      - name: risk_level
        kind: Number
        optional: true
        label: Risk Level
        description: "Risk level (1-5, higher = more risky)"
      - name: default_ports
        kind: Text
        optional: true
        label: Default Ports
        description: "Common ports used by this application"

  - name: URLCategory
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "mdi:web"
    description: "URL category for web filtering"
    label: "URL Category"
    human_friendly_id:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
      - name: description
        kind: Text
        optional: true
      - name: risk_level
        kind: Text
        enum: ["low", "medium", "high", "critical"]
        default_value: "medium"
        optional: false

  - name: SecurityProfile
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "mdi:shield-account"
    description: "Security profile for device/user groups"
    label: "Security Profile"
    human_friendly_id:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
      - name: description
        kind: Text
        optional: true
      - name: antivirus_enabled
        kind: Boolean
        default_value: true
        optional: false
      - name: ips_enabled
        kind: Boolean
        default_value: true
        optional: false
      - name: url_filtering_enabled
        kind: Boolean
        default_value: false
        optional: false
    relationships:
      - name: blocked_url_categories
        peer: SecurityURLCategory
        cardinality: many
        optional: true
        kind: Attribute
      - name: blocked_applications
        peer: SecurityApplication
        cardinality: many
        optional: true
        kind: Attribute

  - name: Schedule
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "mdi:calendar-clock"
    description: "Time-based schedule for rules"
    label: "Schedule"
    human_friendly_id:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
      - name: description
        kind: Text
        optional: true
      - name: days_of_week
        kind: Text
        optional: false
        description: "Comma-separated list (e.g., 'monday,tuesday,friday')"
      - name: start_time
        kind: Text
        optional: false
        description: "Start time in HH:MM format"
      - name: end_time
        kind: Text
        optional: false
        description: "End time in HH:MM format"
      - name: timezone
        kind: Text
        optional: true
        default_value: "UTC"

extensions:
  nodes:
    - kind: LocationGeneric
      relationships:
        - name: policy
          peer: SecurityPolicy
          cardinality: one
          kind: Attribute
