# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"

nodes:
  - name: SegmentSecurityZone
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "carbon:network-3-reference"
    description: "Security zone for network segments"
    label: "Segment Security Zone"
    human_friendly_id:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        unique: true
        optional: false
      - name: trust_level
        kind: Number
        label: Trust Level
        optional: true
        description: "Security trust level (0-100, higher = more trusted)"
      - name: isolation_level
        kind: Dropdown
        description: "Level of network isolation"
        choices:
          - name: strict
            label: Strict Isolation
            description: "Complete isolation with explicit allow rules"
            color: "#E74C3C"
          - name: controlled
            label: Controlled Access
            description: "Controlled access with some defaults"
            color: "#F39C12"
          - name: permissive
            label: Permissive
            description: "Permissive with basic restrictions"
            color: "#27AE60"
        default_value: "controlled"
      - name: description
        kind: Text
        optional: true

  - name: SegmentSecurityProfile
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "mdi:shield-network"
    description: "Security profile for network segments"
    label: "Segment Security Profile"
    human_friendly_id:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
      - name: description
        kind: Text
        optional: true
      - name: default_action
        kind: Text
        enum: ["permit", "deny"]
        default_value: "deny"
        optional: false
        description: "Default action for unmatched traffic"
      - name: enable_micro_segmentation
        kind: Boolean
        default_value: false
        optional: false
        description: "Enable micro-segmentation within the segment"
      - name: enable_dhcp_snooping
        kind: Boolean
        default_value: true
        optional: false
        description: "Enable DHCP snooping protection"
      - name: enable_arp_inspection
        kind: Boolean
        default_value: true
        optional: false
        description: "Enable dynamic ARP inspection"
      - name: max_mac_addresses
        kind: Number
        optional: true
        description: "Maximum MAC addresses allowed per interface"
    relationships:
      - name: allowed_protocols
        peer: SecurityGenericService
        cardinality: many
        optional: true
        kind: Attribute
        identifier: "security_profile__allowed_protocols"
        description: "Protocols allowed by default in this profile"
      - name: blocked_protocols
        peer: SecurityGenericService
        cardinality: many
        optional: true
        kind: Attribute
        identifier: "security_profile__blocked_protocols"
        description: "Protocols explicitly blocked in this profile"

  - name: SegmentAccessControlList
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "mdi:format-list-checks"
    description: "Access Control List for network segments"
    label: "Segment ACL"
    human_friendly_id:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        optional: false
        unique: true
      - name: description
        kind: Text
        optional: true
      - name: acl_type
        kind: Dropdown
        description: "Type of access control list"
        choices:
          - name: standard
            label: Standard ACL
            description: "Source IP based filtering"
            color: "#3498DB"
          - name: extended
            label: Extended ACL
            description: "Source/destination IP and port based filtering"
            color: "#E67E22"
        default_value: "extended"
        optional: false
    relationships:
      - name: rules
        peer: SecuritySegmentACLRule
        cardinality: many
        kind: Component
        optional: true
        description: "ACL rules in this list"

  - name: SegmentACLRule
    namespace: Security
    menu_placement: SecurityPolicy
    include_in_menu: true
    icon: "mdi:format-list-numbered"
    description: "Individual rule in a network segment ACL"
    label: "Segment ACL Rule"
    order_by:
      - index__value
    attributes:
      - name: index
        label: Index
        kind: Number
        optional: false
        order_weight: 1
      - name: name
        label: Name
        kind: Text
        optional: false
        order_weight: 2
      - name: action
        label: Action
        kind: Text
        enum: ["permit", "deny"]
        default_value: permit
        optional: false
        order_weight: 3
      - name: direction
        label: Direction
        kind: Text
        enum: ["ingress", "egress", "bidirectional"]
        default_value: bidirectional
        optional: false
        order_weight: 4
      - name: log
        label: Log
        kind: Boolean
        default_value: false
        optional: true
        order_weight: 5
      - name: description
        label: Description
        kind: Text
        optional: true
        order_weight: 6
    relationships:
      - name: acl
        peer: SecuritySegmentAccessControlList
        cardinality: one
        optional: false
        kind: Attribute
      - name: source_addresses
        peer: SecurityGenericAddress
        cardinality: many
        optional: true
        kind: Attribute
        identifier: "acl_rule__source_addresses"
        description: "Source addresses for this rule"
      - name: destination_addresses
        peer: SecurityGenericAddress
        cardinality: many
        optional: true
        kind: Attribute
        identifier: "acl_rule__destination_addresses"
        description: "Destination addresses for this rule"
      - name: services
        peer: SecurityGenericService
        cardinality: many
        optional: true
        kind: Attribute
        identifier: "acl_rule__services"
        description: "Services/protocols for this rule"

extensions:
  nodes:
    - kind: ServiceNetworkSegment
      relationships:
        - name: security_zone
          peer: SecuritySegmentSecurityZone
          cardinality: one
          optional: true
          kind: Attribute
          description: "Security zone this network segment belongs to"
        - name: security_profile
          peer: SecuritySegmentSecurityProfile
          cardinality: one
          optional: true
          kind: Attribute
          description: "Security profile applied to this network segment"
        - name: access_control_lists
          peer: SecuritySegmentAccessControlList
          cardinality: many
          optional: true
          kind: Attribute
          description: "ACLs applied to this network segment"
      attributes:
        - name: security_enforcement
          kind: Boolean
          default_value: true
          optional: false
          description: "Enable security enforcement for this segment"
        - name: default_deny_all
          kind: Boolean
          default_value: false
          optional: false
          description: "Default deny all traffic not explicitly allowed"
        - name: enable_logging
          kind: Boolean
          default_value: true
          optional: false
          description: "Enable security logging for this segment"