---
apiVersion: infrahub.app/v1
kind: Menu
spec:
  data:
    # ===================== ORGANIZATION =====================
    - namespace: Organization
      name: MainMenu
      label: Organization
      icon: "mdi:domain"
      kind: OrganizationGeneric
      children:
        data:
          - namespace: Organization
            name: Manufacturer
            label: Manufacturers
            kind: OrganizationManufacturer
            icon: "mdi:factory"

          - namespace: Organization
            name: Provider
            label: Providers
            kind: OrganizationProvider
            icon: "mdi:cloud-outline"

          - namespace: Organization
            name: Customer
            label: Customers
            kind: OrganizationCustomer
            icon: "mdi:account-group"

    # ===================== LOCATION =====================
    - namespace: Location
      name: Generic
      label: Location
      kind: LocationGeneric
      icon: "mdi:map-marker"

    # ===================== TOPOLOGY & DESIGN =====================
    - namespace: Topology
      name: TopologyMenu
      label: Network Topologies
      icon: "mdi:network"
      children:
        data:
          - namespace: Topology
            name: DeploymentMenu
            label: Deployments
            icon: "mdi:server-network"
            children:
              data:
                - name: DataCenter
                  namespace: Topology
                  label: Data Centers
                  kind: TopologyDataCenter
                  icon: "mdi:server-network"

                - name: ColocationCenter
                  namespace: Topology
                  label: Colocation Centers
                  kind: TopologyColocationCenter
                  icon: "mdi:office-building"

                - name: BranchOffice
                  namespace: Topology
                  label: Branch Offices
                  kind: TopologyBranchOffice
                  icon: "mdi:office-building-outline"

          - namespace: Design
            name: DesignMenu
            label: Design Patterns
            icon: "mdi:drawing"
            children:
              data:
                - name: Topology
                  namespace: Design
                  label: Design Templates
                  kind: DesignTopology
                  icon: "mdi:vector-arrange-above"

                - name: Element
                  namespace: Design
                  label: Design Elements
                  kind: DesignElement
                  icon: "mdi:cube-outline"

    # ===================== SERVICES =====================
    - namespace: Service
      name: Generic
      label: Services
      icon: "mdi:cog-box"
      children:
        data:
          # --------- Security Services ---------
          # - namespace: Service
          #   name: SecurityMenu
          #   label: Security Services
          #   icon: "mdi:shield-check"
          #   children:
          #     data:
          #       - namespace: Service
          #         name: SecurityService
          #         label: Security Services
          #         kind: ServiceSecurityService
          #         icon: "mdi:shield-check"
          #       - namespace: Service
          #         name: SecurityServiceEndpoint
          #         label: Security Endpoints
          #         kind: ServiceSecurityServiceEndpoint
          #         icon: "mdi:ethernet"
          #       - namespace: Service
          #         name: SecurityPolicyGroup
          #         label: Policy Groups
          #         kind: ServiceSecurityPolicyGroup
          #         icon: "mdi:folder-multiple"
          #       - namespace: Service
          #         name: ThreatIntelligenceService
          #         label: Threat Intelligence
          #         kind: ServiceThreatIntelligenceService
          #         icon: "mdi:shield-bug"

          # --------- Cloud Security Services ---------
          # - namespace: Service
          #   name: CloudSecurityMenu
          #   label: Cloud Security Services
          #   icon: "mdi:cloud-lock-outline"
          #   children:
          #     data:
          #       - namespace: Service
          #         name: CloudSecurityService
          #         label: Cloud Security Services
          #         kind: ServiceCloudSecurityService
          #         icon: "mdi:cloud-lock-outline"
          #       - namespace: Service
          #         name: CloudGateway
          #         label: Cloud Gateways
          #         kind: ServiceCloudGateway
          #         icon: "mdi:router-wireless"
          #       - namespace: Service
          #         name: CloudSecurityPolicyGroup
          #         label: Cloud Policy Groups
          #         kind: ServiceCloudSecurityPolicyGroup
          #         icon: "mdi:shield-check-outline"

          # --------- Network Services ---------
          - namespace: Service
            name: NetworkMenu
            label: Network Services
            icon: "mdi:lan"
            children:
              data:
                - namespace: Service
                  name: NetworkSegment
                  label: Network Segments
                  kind: ServiceNetworkSegment
                  icon: "mdi:lan"
                - namespace: Service
                  name: Loadbalancer
                  label: Load Balancers
                  kind: ServiceVIP
                  icon: "carbon:floating-ip"
                  description: "Load balancers that distribute traffic across multiple servers."
                - namespace: Service
                  name: NTPServer
                  label: NTP Servers
                  kind: NetworkNTPServer
                  icon: "mdi:clock-outline"
                - namespace: Service
                  name: NameServer
                  label: DNS Servers
                  kind: NetworkNameServer
                  icon: "mdi:dns"
          # --------- Routing & Peering ---------
          - namespace: Service
            name: RoutingMenu
            label: Routing & Peering
            icon: "mdi:router"
            children:
              data:
                - namespace: Service
                  name: BGPPeering
                  label: "BGP Peering Sessions"
                  kind: ServiceBGPPeering
                  icon: "carbon:network-4-reference"
                  description: "BGP peering sessions with internal devices and external partners"

                - namespace: Service
                  name: OSPFPeering
                  label: "OSPF Peering Sessions"
                  kind: ServiceOSPFPeering
                  icon: "carbon:network-4-reference"
                  description: "OSPF peering sessions with internal devices and external partners"

                - namespace: Service
                  name: PeeringPolicy
                  label: "Peering Policies"
                  kind: ServicePeeringPolicy
                  icon: "carbon:policy"
                  description: "Routing policies for peering relationships"
    # ==================== SECURITY MANAGEMENT =====================
    - namespace: Security
      name: SecurityMenu
      label: Security Management
      icon: "mdi:security"
      children:
        data:
          # --------- Policies & Rules ---------
          - namespace: Security
            name: PoliciesMenu
            label: "Policies & Rules"
            icon: "mdi:file-document-multiple"
            children:
              data:
                - namespace: Security
                  name: Policy
                  label: "Security Policies"
                  kind: SecurityPolicy
                  icon: "mdi:file-document-outline"
                - namespace: Security
                  name: PolicyRule
                  label: "Policy Rules"
                  kind: SecurityPolicyRule
                  icon: "mdi:file-document-edit-outline"

          # --------- Security Zones ---------
          - namespace: Security
            name: ZonesMenu
            label: "Security Zones"
            icon: "mdi:shield-outline"
            children:
              data:
                - namespace: Security
                  name: Zone
                  label: "Security Zones"
                  kind: SecurityZone
                  icon: "mdi:shield-lock"

          # --------- Security Objects ---------
          - namespace: Security
            name: ObjectsMenu
            label: "Security Objects"
            icon: "mdi:cube-outline"
            children:
              data:
                - namespace: Security
                  name: AddressesSubmenu
                  label: "Addresses & Networks"
                  icon: "mdi:ip-network"
                  children:
                    data:
                      - namespace: Security
                        name: IPAddress
                        label: "IP Addresses"
                        kind: SecurityIPAddress
                        icon: "mdi:ip-network"
                      - namespace: Security
                        name: Prefix
                        label: "IP Prefixes"
                        kind: SecurityPrefix
                        icon: "mdi:ip-network"
                      - namespace: Security
                        name: IPRange
                        label: "IP Ranges"
                        kind: SecurityIPRange
                        icon: "mdi:ip-network"
                      - namespace: Security
                        name: FQDN
                        label: "Domain Names"
                        kind: SecurityFQDN
                        icon: "mdi:web"
                      - namespace: Security
                        name: AddressGroup
                        label: "Address Groups"
                        kind: SecurityAddressGroup
                        icon: "mdi:folder-network"

                - namespace: Security
                  name: ServicesSubmenu
                  label: "Services & Applications"
                  icon: "mdi:application"
                  children:
                    data:
                      - namespace: Security
                        name: Service
                        label: "Network Services"
                        kind: SecurityService
                        icon: "mdi:network"
                      - namespace: Security
                        name: ServiceRange
                        label: "Service Ranges"
                        kind: SecurityServiceRange
                        icon: "mdi:network"
                      - namespace: Security
                        name: ServiceGroup
                        label: "Service Groups"
                        kind: SecurityServiceGroup
                        icon: "mdi:folder-network"
                      - namespace: Security
                        name: Application
                        label: "Applications"
                        kind: SecurityApplication
                        icon: "mdi:application"
                      - namespace: Security
                        name: URLCategory
                        label: "URL Categories"
                        kind: SecurityURLCategory
                        icon: "mdi:web"

                - namespace: Security
                  name: NetworkSegmentSecurityMenu
                  label: "Network Segment Security"
                  icon: "mdi:shield-network"
                  children:
                    data:
                      - namespace: Security
                        name: SegmentSecurityZone
                        label: "Segment Security Zones"
                        kind: SecuritySegmentSecurityZone
                        icon: "mdi:shield-lock-outline"
                      - namespace: Security
                        name: SegmentSecurityProfile
                        label: "Segment Security Profiles"
                        kind: SecuritySegmentSecurityProfile
                        icon: "mdi:shield-check-outline"
                      - namespace: Security
                        name: SegmentAccessControlList
                        label: "Segment ACLs"
                        kind: SecuritySegmentAccessControlList
                        icon: "mdi:playlist-check"
                      - namespace: Security
                        name: SegmentACLRule
                        label: "Segment ACL Rules"
                        kind: SecuritySegmentACLRule
                        icon: "mdi:playlist-edit"

                - namespace: Security
                  name: ProfilesSchedulesMenu
                  label: "Profiles & Schedules"
                  icon: "mdi:shield-check"
                  children:
                    data:
                      - namespace: Security
                        name: SecurityProfile
                        label: "Security Profiles"
                        kind: SecuritySecurityProfile
                        icon: "mdi:shield-check"
                      - namespace: Security
                        name: Schedule
                        label: "Schedules"
                        kind: SecuritySchedule
                        icon: "mdi:calendar-clock"

    # ===================== DEVICE MANAGEMENT =====================
    - namespace: Dcim
      name: DeviceManagementMenu
      label: Device Management
      icon: "mdi:server"
      children:
        data:
          # --------- Core Infrastructure ---------
          - namespace: Dcim
            name: DevicesMenu
            label: "Infrastructure"
            icon: "mdi:server"
            children:
              data:
                - namespace: Dcim
                  name: GenericDevice
                  label: All Devices
                  kind: DcimGenericDevice
                  icon: "mdi:server"

                - name: Interface
                  namespace: Dcim
                  label: "Interfaces"
                  icon: "mdi:ethernet"
                  kind: DcimInterface

                - name: GenericSFP
                  namespace: Dcim
                  label: "SFP Modules"
                  icon: "mdi:expansion-card"
                  kind: DcimGenericSFP

          # --------- Network Management ---------


          # --------- Device Types & Platforms ---------
          - namespace: Dcim
            name: TypesMenu
            label: "Types & Platforms"
            icon: "mdi:cog"
            children:
              data:
                - namespace: Dcim
                  name: Platform
                  label: Platforms
                  kind: DcimPlatform
                  icon: "mdi:chip"

                - namespace: Dcim
                  name: DeviceType
                  label: Device Types
                  kind: DcimDeviceType
                  icon: "mdi:package-variant"

    # ===================== ROUTING =====================
    - namespace: Routing
      name: ManagementMenu
      label: Routing Management
      icon: "mdi:router"
      children:
        data:
          - namespace: Routing
            name: BGPMenu
            label: "BGP Management"
            icon: "mdi:router-network"
            children:
              data:
                - namespace: Routing
                  name: AutonomousSystem
                  label: "Autonomous Systems"
                  kind: RoutingAutonomousSystem
                  icon: "mdi:bank-circle-outline"

                - namespace: Routing
                  name: BGPService
                  label: Service BGP
                  kind: ServiceBGP
                  icon: "carbon:ibm-cloud-internet-services"

                - namespace: Routing
                  name: BGPPeerGroup
                  label: "BGP Peer Groups"
                  kind: RoutingBGPPeerGroup
                  icon: "mdi:view-grid-plus-outline"

                - namespace: Routing
                  name: BGPCommunity
                  label: "BGP Communities"
                  kind: RoutingBGPCommunity
                  icon: "mdi:tag-multiple"

          - namespace: Routing
            name: OSPFMenu
            label: "OSPF Management"
            icon: "mdi:network-outline"
            children:
              data:
                - namespace: Routing
                  name: OSPFArea
                  label: OSPF Areas
                  kind: RoutingOSPFArea
                  icon: "mdi:square-rounded-outline"

                - namespace: Routing
                  name: OSPFService
                  label: Service OSPF
                  kind: ServiceOSPF
                  icon: "carbon:ibm-cloud-internet-services"

                - namespace: Routing
                  name: OSPFInterface
                  label: OSPF Interface Profiles
                  kind: RoutingOSPFInterface
                  icon: "mdi:shield-check"

          - namespace: Routing
            name: PIMMenu
            label: PIM Management
            icon: "mdi:pim-outline"
            children:
              data:
                - namespace: Routing
                  name: PIMService
                  label: Service PIM
                  kind: ServicePIM
                  icon: "carbon:ibm-cloud-internet-services"

                - namespace: Routing
                  name: PIMInterface
                  label: PIM Interface Profiles
                  kind: RoutingPIMInterface
                  icon: "mdi:ethernet"

    # ===================== LOAD BALANCING =====================

    - namespace: Loadbalancing
      name: ManagementMenu
      label: LB Management
      icon: carbon:load-balancer-global
      children:
        data:

          - namespace: Loadbalancing
            name: HealthCheck
            label: Health-Checks
            kind: LoadbalancerHealthCheck
            icon: "tabler:checkup-list"
          - namespace: Loadbalancing
            name: Servers
            label: Backend Servers
            kind: LoadbalancerServer
            icon: mdi:server-plus
