---
apiVersion: infrahub.app/v1
kind: Menu
spec:
  data:
    - namespace: Organization
      name: MainMenu
      label: Organization
      icon: "mdi:domain"
      kind: OrganizationGeneric
      children:
        data:
          - namespace: Organization
            name: Manufacturer
            label: Manufacturers
            kind: OrganizationManufacturer
            icon: "mdi:domain"

          - namespace: Organization
            name: Provider
            label: Providers
            kind: OrganizationProvider
            icon: "mdi:domain"

          - namespace: Organization
            name: Customer
            label: Customers
            kind: OrganizationCustomer
            icon: "mdi:domain"

    - namespace: Location
      name: Generic
      label: Location
      kind: LocationGeneric
      icon: "mingcute:location-line"

    - namespace: Topology
      name: TopologyMenu
      label: Topology Management
      icon: "tabler:topology-star-ring-3"
      children:
        data:
          - namespace: Topology
            name: DesignMenu
            label: Designs
            icon: "carbon:subnet-acl-rules"
            children:
              data:
                - name: Topology
                  namespace: Design
                  label: Design Patterns
                  kind: DesignTopology
                  icon: "carbon:data-center"

                - name: Element
                  namespace: Design
                  label: Design Elements
                  kind: DesignElement
                  icon: "subway:switch"

          - namespace: Topology
            name: DeploymentMenu
            label: Topology Deployments
            icon: "carbon:subnet-acl-rules"
            children:
              data:
                - name: DataCenter
                  namespace: Topology
                  label: Data Center
                  kind: TopologyDataCenter
                  icon: "carbon:data-center"

                - name: ColocationCenter
                  namespace: Topology
                  label: Colocation Center
                  kind: TopologyColocationCenter
                  icon: "carbon:data-center"

                - name: CampusOffice
                  namespace: Topology
                  label: Campus Office
                  kind: TopologyCampusOffice
                  icon: "solar:buildings-3-linear"

                - name: BranchOffice
                  namespace: Topology
                  label: Branch Office
                  kind: TopologyBranchOffice
                  icon: "tabler:building"

    - namespace: Security
      name: SecurityMenu
      label: Security Management
      icon: "oui:integration-security"
      kind: SecurityGeneric
      children:
        data:
          - namespace: Security
            name: FiltersMenu
            label: Filters
            icon: "carbon:subnet-acl-rules"
            children:
              data:
                - namespace: Security
                  name: IPProtocol
                  label: "IP Protocols"
                  kind: SecurityIPProtocol
                  icon: "mdi:protocol"
                - namespace: Security
                  name: IPAddress
                  label: "IP Address"
                  kind: SecurityIPAddress
                  icon: "mdi:ip-outline"
                - namespace: Security
                  name: IPAMIPAddress
                  label: "IPAM IP Address"
                  kind: SecurityIpamIPAddress
                  icon: "mdi:ip-outline"
                - namespace: Security
                  name: FQDN
                  label: "FQDN"
                  kind: SecurityFQDN
                  icon: "eos-icons:dns"
                - namespace: Security
                  name: Prefix
                  label: "Prefix"
                  kind: SecurityPrefix
                  icon: "mdi:ip-network-outline"
                - namespace: Security
                  name: IPAMIPPrefix
                  label: "IPAM Prefix"
                  kind: SecurityIpamPrefix
                  icon: "mdi:ip-network-outline"
                - namespace: Security
                  name: IPRange
                  label: "IP Range"
                  kind: SecurityIPRange
                  icon: "mdi:ip-network-outline"
                - namespace: Security
                  name: Service
                  label: "Services"
                  kind: SecurityService
                  icon: "mdi:domain"
                - namespace: Security
                  name: ServiceRange
                  label: "Service Ranges"
                  kind: SecurityServiceRange
                  icon: "mdi:domain"
                - namespace: Security
                  name: AddressGroup
                  label: "Address Group"
                  kind: SecurityAddressGroup
                  icon: "material-symbols:menu-book-outline-rounded"
                - namespace: Security
                  name: ServiceGroup
                  label: "Service Group"
                  kind: SecurityServiceGroup
                  icon: "material-symbols:menu-book-outline-rounded"

          - namespace: Security
            name: Zone
            label: Security zone
            kind: SecurityZone
            icon: "game-icons:fire-zone"

          - namespace: Security
            name: PolicyRule
            label: Policy Rule
            kind: SecurityPolicyRule
            icon: "material-symbols:policy"

          - namespace: Security
            name: Policy
            label: Policy
            kind: SecurityPolicy
            icon: "mdi:domain"

    - namespace: Dcim
      name: DeviceManagementMenu
      label: Device Management
      icon: "mdi:server"
      children:
        data:
          - namespace: Dcim
            name: NetworkDeviceMenu
            label: Network Devices
            icon: "mdi:server"
            children:
              data:
                - namespace: Dcim
                  name: Device
                  label: Routers & Switches
                  kind: DcimDevice
                  icon: "subway:switch"
                - namespace: Dcim
                  name: Firewall
                  label: Firewalls
                  kind: DcimFirewall
                  icon: "clarity:firewall-line"
    #             - namespace: Infra
    #               name: Loadbalancer
    #               label: Load Balancers
    #               kind: InfraLoadbalancer
    #               icon: "carbon:load-balancer-classic"
    #             - namespace: Infra
    #               name: Console
    #               label: Console Servers
    #               kind: InfraConsole
    #               icon: "mdi:console-line"
          - namespace: Network
            name: ServerMenu
            label: Servers
            icon: "mdi:server"
            children:
              data:
                - namespace: Network
                  name: NTPServer
                  label: NTP Servers
                  kind: NetworkNTPServer
                  icon: "iconoir:time-zone"
                - namespace: Network
                  name: NameServer
                  label: DNS Servers
                  kind: NetworkNameServer
                  icon: "mdi:dns"
    #             - namespace: Infra
    #               name: DhcpServer
    #               label: DHCP Servers
    #               kind: InfraDhcpServer
    #               icon: "eos-icons:ip"
    #             - namespace: Infra
    #               name: CollectorServer
    #               label: Collector Servers
    #               kind: InfraCollectorServer
    #               icon: "mdi:server-network"

          - namespace: Dcim
            name: GenericDevice
            label: All Devices
            kind: DcimGenericDevice
            icon: "mdi:server"

          - name: Interface
            namespace: Dcim
            label: "All Interfaces"
            icon: "mdi:ethernet"
            kind: DcimInterface

          - name: GenericSFP
            namespace: Dcim
            label: "All SFPs"
            icon: "mdi:gpu"
            kind: DcimGenericSFP

    #       - namespace: Infra
    #         name: MlagMenu
    #         label: Link Aggregation
    #         icon: "eos-icons:cluster-management"
    #         children:
    #           data:
    #             - name: MlagDomain
    #               namespace: Infra
    #               label: "MLAG Domains"
    #               icon: "eos-icons:cluster-management"
    #               kind: InfraMlagDomain

    #             - name: MlagInterface
    #               namespace: Infra
    #               label: "MLAG Interfaces"
    #               icon: "mdi:ethernet"
    #               kind: InfraMlagInterface

          - namespace: Dcim
            name: Platform
            label: Platform
            kind: DcimPlatform
            icon: "mdi:application-cog-outline"

          - namespace: Dcim
            name: DeviceType
            label: Device Type
            kind: DcimDeviceType
            icon: "mdi:application-settings-outline"

    - namespace: Infra
      name: CircuitMenu
      label: Circuit Management
      icon: "mdi:transit-connection-variant"
      children:
        data:
          - name: Circuit
            namespace: Dcim
            label: "Circuit"
            icon: "mdi:cable-data"
            kind: DcimCircuit

    # - namespace: Infra
    #   name: NetworkMenu
    #   label: Network Segment
    #   icon: "mdi:lan"
    #   children:
    #     data:
    #       - name: VLAN
    #         namespace: Infra
    #         label: "VLAN"
    #         icon: "mdi:lan-pending"
    #         kind: InfraVLAN
    #       - name: SSID
    #         namespace: Infra
    #         label: "SSID"
    #         icon: "mdi:wireless"
    #         kind: InfraSSID

    - namespace: Routing
      name: Menu
      label: Routing & Peering
      icon: "mdi:router"
      children:
        data:
          - name: VRF
            namespace: Ipam
            label: "VRF"
            icon: "mdi:router"
            kind: IpamVRF
          - name: BGP
            namespace: Routing
            label: "BGP"
            icon: "mdi:router"
            children:
              data:
                - name: AutonomousSystem
                  namespace: Routing
                  label: "Autonomous System"
                  icon: "mdi:bank-circle-outline"
                  kind: RoutingAutonomousSystem

                - name: BGPSession
                  namespace: Routing
                  label: "BGP Session"
                  icon: "mdi:router"
                  kind: RoutingBGPSession

                - name: BGPPeerGroup
                  namespace: Routing
                  label: "BGP Peer Group"
                  icon: "mdi:view-grid-plus-outline"
                  kind: RoutingBGPPeerGroup

    - namespace: Infra
      name: Service
      label: Services
      icon: "carbon:container-services"
      children:
        data:
          - namespace: Infra
            name: BackBoneService
            label: "Backbone Service"
            kind: InfraBackBoneService
            icon: "carbon:flow-connection"
          - namespace: Infra
            name: Layer2NetworkService
            label: "Layer2 Network Service"
            kind: InfraLayer2NetworkService
            icon: "carbon:vlan"
          - namespace: Infra
            name: Layer3NetworkService
            label: "Layer3 Network Service"
            kind: InfraLayer3NetworkService
            icon: "carbon:container-services"
