---
apiVersion: infrahub.app/v1
kind: Menu
spec:
  data:
    # ===================== ORGANIZATION =====================
    - namespace: Organization
      name: MainMenu
      label: Organization
      icon: "mdi:domain"
      kind: OrganizationGeneric
      children:
        data:
          - namespace: Organization
            name: Manufacturer
            label: Manufacturers
            kind: OrganizationManufacturer
            icon: "mdi:factory"

          - namespace: Organization
            name: Provider
            label: Providers
            kind: OrganizationProvider
            icon: "mdi:cloud-outline"

          - namespace: Organization
            name: Customer
            label: Customers
            kind: OrganizationCustomer
            icon: "mdi:account-group"

    # ===================== LOCATION =====================
    - namespace: Location
      name: Generic
      label: Location
      kind: LocationGeneric
      icon: "mdi:map-marker"

    # ===================== TOPOLOGY & DESIGN =====================
    - namespace: Topology
      name: TopologyMenu
      label: Network Topologies
      icon: "mdi:network"
      children:
        data:
          - namespace: Topology
            name: DeploymentMenu
            label: Deployments
            icon: "mdi:server-network"
            children:
              data:
                - name: DataCenter
                  namespace: Topology
                  label: Data Centers
                  kind: TopologyDataCenter
                  icon: "mdi:server-network"

                - name: ColocationCenter
                  namespace: Topology
                  label: Colocation Centers
                  kind: TopologyColocationCenter
                  icon: "mdi:office-building"

                - name: BranchOffice
                  namespace: Topology
                  label: Branch Offices
                  kind: TopologyBranchOffice
                  icon: "mdi:office-building-outline"

          - namespace: Design
            name: DesignMenu
            label: Design Patterns
            icon: "mdi:drawing"
            children:
              data:
                - name: Topology
                  namespace: Design
                  label: Design Templates
                  kind: DesignTopology
                  icon: "mdi:vector-arrange-above"

                - name: Element
                  namespace: Design
                  label: Design Elements
                  kind: DesignElement
                  icon: "mdi:cube-outline"

    # ===================== SERVICES =====================
    - namespace: Service
      name: Generic
      label: Services
      icon: "mdi:cog-box"
      children:
        data:
          # --------- Security Services ---------
          - namespace: Service
            name: SecurityMenu
            label: Security Services
            icon: "mdi:shield-check"
            children:
              data:
                - namespace: Service
                  name: SecurityService
                  label: Security Services
                  kind: ServiceSecurityService
                  icon: "mdi:shield-check"
                - namespace: Service
                  name: SecurityServiceEndpoint
                  label: Security Endpoints
                  kind: ServiceSecurityServiceEndpoint
                  icon: "mdi:ethernet"
                - namespace: Service
                  name: SecurityPolicyGroup
                  label: Policy Groups
                  kind: ServiceSecurityPolicyGroup
                  icon: "mdi:folder-multiple"
                - namespace: Service
                  name: ThreatIntelligenceService
                  label: Threat Intelligence
                  kind: ServiceThreatIntelligenceService
                  icon: "mdi:shield-bug"

          # --------- Network Services ---------
          - namespace: Service
            name: NetworkMenu
            label: Network Services
            icon: "mdi:lan"
            children:
              data:
                - namespace: Service
                  name: NetworkSegment
                  label: Network Segments
                  kind: ServiceNetworkSegment
                  icon: "mdi:lan"

          # --------- Routing & Peering ---------
          - namespace: Service
            name: RoutingMenu
            label: Routing & Peering
            icon: "mdi:router"
            children:
              data:
                - name: BGPMenu
                  namespace: Service
                  label: "BGP Services"
                  icon: "mdi:router"
                  children:
                    data:
                      - name: AutonomousSystem
                        namespace: Service
                        label: "Autonomous Systems"
                        icon: "mdi:bank-circle-outline"
                        kind: ServiceAutonomousSystem

                      - name: BGPSession
                        namespace: Service
                        label: "BGP Sessions"
                        icon: "mdi:router-network"
                        kind: ServiceBGPSession

                      - name: BGPPeerGroup
                        namespace: Service
                        label: "BGP Peer Groups"
                        icon: "mdi:account-group"
                        kind: ServiceBGPPeerGroup

                      - name: BGPCommunity
                        namespace: Service
                        label: "BGP Communities"
                        icon: "mdi:tag-multiple"
                        kind: ServiceBGPCommunity

                - name: OSPFMenu
                  namespace: Service
                  label: "OSPF Services"
                  icon: "mdi:router-wireless"
                  children:
                    data:
                      - namespace: Service
                        name: OSPFArea
                        label: OSPF Areas
                        kind: ServiceOSPFArea
                        icon: "mdi:circle-outline"
                      - namespace: Service
                        name: OSPF
                        label: OSPF Instances
                        kind: ServiceOSPF
                        icon: "mdi:router-wireless"
                      - namespace: Service
                        name: OSPFInterfaces
                        label: OSPF Interfaces
                        kind: ServiceOSPFInterface
                        icon: "mdi:ethernet"

                - namespace: Service
                  name: RoutingPolicy
                  label: Routing Policies
                  kind: ServiceRoutingPolicy
                  icon: "mdi:file-document-outline"

    # ===================== SECURITY MANAGEMENT =====================
    - namespace: Security
      name: SecurityMenu
      label: Security Management
      icon: "mdi:security"
      children:
        data:
          # --------- Policies & Rules ---------
          - namespace: Security
            name: PoliciesMenu
            label: "Policies & Rules"
            icon: "mdi:file-document-multiple"
            children:
              data:
                - namespace: Security
                  name: Policy
                  label: "Security Policies"
                  kind: SecurityPolicy
                  icon: "mdi:shield-check"
                - namespace: Security
                  name: PolicyRule
                  label: "Policy Rules"
                  kind: SecurityPolicyRule
                  icon: "mdi:format-list-bulleted"

          # --------- Security Zones ---------
          - namespace: Security
            name: ZonesMenu
            label: "Security Zones"
            icon: "mdi:shield-outline"
            children:
              data:
                - namespace: Security
                  name: Zone
                  label: "Security Zones"
                  kind: SecurityZone
                  icon: "mdi:shield-outline"

          # --------- Security Objects ---------
          - namespace: Security
            name: ObjectsMenu
            label: "Security Objects"
            icon: "mdi:cube-outline"
            children:
              data:
                - namespace: Security
                  name: AddressesSubmenu
                  label: "Addresses & Networks"
                  icon: "mdi:ip-network"
                  children:
                    data:
                      - namespace: Security
                        name: IPAddress
                        label: "IP Addresses"
                        kind: SecurityIPAddress
                        icon: "mdi:ip"
                      - namespace: Security
                        name: IpamIPAddress
                        label: "IPAM IP Addresses"
                        kind: SecurityIpamIPAddress
                        icon: "mdi:ip-outline"
                      - namespace: Security
                        name: Prefix
                        label: "IP Prefixes"
                        kind: SecurityPrefix
                        icon: "mdi:ip-network-outline"
                      - namespace: Security
                        name: IpamPrefix
                        label: "IPAM Prefixes"
                        kind: SecurityIpamPrefix
                        icon: "mdi:ip-network"
                      - namespace: Security
                        name: IPRange
                        label: "IP Ranges"
                        kind: SecurityIPRange
                        icon: "mdi:format-list-numbered"
                      - namespace: Security
                        name: FQDN
                        label: "Domain Names"
                        kind: SecurityFQDN
                        icon: "mdi:dns"
                      - namespace: Security
                        name: AddressGroup
                        label: "Address Groups"
                        kind: SecurityAddressGroup
                        icon: "mdi:folder"

                - namespace: Security
                  name: ServicesSubmenu
                  label: "Services & Applications"
                  icon: "mdi:application"
                  children:
                    data:
                      - namespace: Security
                        name: Service
                        label: "Network Services"
                        kind: SecurityService
                        icon: "mdi:application-outline"
                      - namespace: Security
                        name: ServiceRange
                        label: "Service Ranges"
                        kind: SecurityServiceRange
                        icon: "mdi:format-list-numbered"
                      - namespace: Security
                        name: ServiceGroup
                        label: "Service Groups"
                        kind: SecurityServiceGroup
                        icon: "mdi:folder-multiple"
                      - namespace: Security
                        name: Application
                        label: "Applications"
                        kind: SecurityApplication
                        icon: "mdi:application"

                - namespace: Security
                  name: WebSecurityMenu
                  label: "Web Security"
                  icon: "mdi:web"
                  children:
                    data:
                      - namespace: Security
                        name: URLCategory
                        label: "URL Categories"
                        kind: SecurityURLCategory
                        icon: "mdi:web"

    # ===================== DEVICE MANAGEMENT =====================
    - namespace: Dcim
      name: DeviceManagementMenu
      label: Device Management
      icon: "mdi:server"
      children:
        data:
          # --------- Core Infrastructure ---------
          - namespace: Dcim
            name: DevicesMenu
            label: "Infrastructure"
            icon: "mdi:server"
            children:
              data:
                - namespace: Dcim
                  name: GenericDevice
                  label: All Devices
                  kind: DcimGenericDevice
                  icon: "mdi:server"

                - name: Interface
                  namespace: Dcim
                  label: "Interfaces"
                  icon: "mdi:ethernet"
                  kind: DcimInterface

                - name: GenericSFP
                  namespace: Dcim
                  label: "SFP Modules"
                  icon: "mdi:expansion-card"
                  kind: DcimGenericSFP

          # --------- Network Management ---------
          - namespace: Network
            name: ServerMenu
            label: Network Services
            icon: "mdi:server-network"
            children:
              data:
                - namespace: Network
                  name: NTPServer
                  label: NTP Servers
                  kind: NetworkNTPServer
                  icon: "mdi:clock-outline"
                - namespace: Network
                  name: NameServer
                  label: DNS Servers
                  kind: NetworkNameServer
                  icon: "mdi:dns"

          # --------- Device Types & Platforms ---------
          - namespace: Dcim
            name: TypesMenu
            label: "Types & Platforms"
            icon: "mdi:cog"
            children:
              data:
                - namespace: Dcim
                  name: Platform
                  label: Platforms
                  kind: DcimPlatform
                  icon: "mdi:chip"

                - namespace: Dcim
                  name: DeviceType
                  label: Device Types
                  kind: DcimDeviceType
                  icon: "mdi:package-variant"


