---
apiVersion: infrahub.app/v1
kind: Menu
spec:
  data:
    # ===================== ORGANIZATION =====================
    - namespace: Organization
      name: MainMenu
      label: Organization
      icon: "mdi:domain"
      kind: OrganizationGeneric
      children:
        data:
          - namespace: Organization
            name: Manufacturer
            label: Manufacturers
            kind: OrganizationManufacturer
            icon: "mdi:factory"

          - namespace: Organization
            name: Provider
            label: Providers
            kind: OrganizationProvider
            icon: "mdi:cloud-outline"

          - namespace: Organization
            name: Customer
            label: Customers
            kind: OrganizationCustomer
            icon: "mdi:account-group"

    # ===================== LOCATION =====================
    - namespace: Location
      name: Generic
      label: Location
      kind: LocationGeneric
      icon: "mdi:map-marker"

    # ===================== TOPOLOGY & DESIGN =====================
    - namespace: Topology
      name: TopologyMenu
      label: Network Topologies
      icon: "mdi:network"
      children:
        data:
          - namespace: Topology
            name: DeploymentMenu
            label: Deployments
            icon: "mdi:server-network"
            children:
              data:
                - name: DataCenter
                  namespace: Topology
                  label: Data Centers
                  kind: TopologyDataCenter
                  icon: "mdi:server-network"

                - name: ColocationCenter
                  namespace: Topology
                  label: Colocation Centers
                  kind: TopologyColocationCenter
                  icon: "mdi:office-building"

                - name: BranchOffice
                  namespace: Topology
                  label: Branch Offices
                  kind: TopologyBranchOffice
                  icon: "mdi:office-building-outline"

          - namespace: Design
            name: DesignMenu
            label: Design Patterns
            icon: "mdi:drawing"
            children:
              data:
                - name: Topology
                  namespace: Design
                  label: Design Templates
                  kind: DesignTopology
                  icon: "mdi:vector-arrange-above"

                - name: Element
                  namespace: Design
                  label: Design Elements
                  kind: DesignElement
                  icon: "mdi:cube-outline"

    # ===================== SERVICES =====================
    - namespace: Service
      name: Generic
      label: Services
      icon: "mdi:cog-box"
      children:
        data:
          # --------- Security Services ---------
          - namespace: Service
            name: SecurityMenu
            label: Security Services
            icon: "mdi:shield-check"
            children:
              data:
                - namespace: Service
                  name: SecurityService
                  label: Security Services
                  kind: ServiceSecurityService
                  icon: "mdi:shield-check"
                - namespace: Service
                  name: SecurityServiceEndpoint
                  label: Security Endpoints
                  kind: ServiceSecurityServiceEndpoint
                  icon: "mdi:ethernet"
                - namespace: Service
                  name: SecurityPolicyGroup
                  label: Policy Groups
                  kind: ServiceSecurityPolicyGroup
                  icon: "mdi:folder-multiple"
                - namespace: Service
                  name: ThreatIntelligenceService
                  label: Threat Intelligence
                  kind: ServiceThreatIntelligenceService
                  icon: "mdi:shield-bug"

          # --------- Network Services ---------
          - namespace: Service
            name: NetworkMenu
            label: Network Services
            icon: "mdi:lan"
            children:
              data:
                - namespace: Service
                  name: NetworkSegment
                  label: Network Segments
                  kind: ServiceNetworkSegment
                  icon: "mdi:lan"

          # --------- Routing & Peering ---------
          - namespace: Service
            name: RoutingMenu
            label: Routing & Peering
            icon: "mdi:router"
            children:
              data:
                - namespace: Service
                  name: BGPFabricMenu
                  label: Fabric BGP
                  kind: ServiceBGP
                  icon: "carbon:ibm-cloud-internet-services"
                - namespace: Service
                  name: OSPFFabricMenu
                  label: Fabric OSPF
                  kind: ServiceOSPF
                  icon: "carbon:ibm-cloud-internet-services"
    # ==================== SECURITY MANAGEMENT =====================
    - namespace: Security
      name: SecurityMenu
      label: Security Management
      icon: "mdi:security"
      children:
        data:
          # --------- Policies & Rules ---------
          - namespace: Security
            name: PoliciesMenu
            label: "Policies & Rules"
            icon: "mdi:file-document-multiple"
            children:
              data:
                - namespace: Security
                  name: Policy
                  label: "Security Policies"
                  kind: SecurityPolicy
                  icon: "mdi:shield-check"
                - namespace: Security
                  name: PolicyRule
                  label: "Policy Rules"
                  kind: SecurityPolicyRule
                  icon: "mdi:format-list-bulleted"

          # --------- Security Zones ---------
          - namespace: Security
            name: ZonesMenu
            label: "Security Zones"
            icon: "mdi:shield-outline"
            children:
              data:
                - namespace: Security
                  name: Zone
                  label: "Security Zones"
                  kind: SecurityZone
                  icon: "mdi:shield-outline"

          # --------- Security Objects ---------
          - namespace: Security
            name: ObjectsMenu
            label: "Security Objects"
            icon: "mdi:cube-outline"
            children:
              data:
                - namespace: Security
                  name: AddressesSubmenu
                  label: "Addresses & Networks"
                  icon: "mdi:ip-network"
                  children:
                    data:
                      - namespace: Security
                        name: IPAddress
                        label: "IP Addresses"
                        kind: SecurityIPAddress
                        icon: "mdi:ip"
                      - namespace: Security
                        name: IpamIPAddress
                        label: "IPAM IP Addresses"
                        kind: SecurityIpamIPAddress
                        icon: "mdi:ip-outline"
                      - namespace: Security
                        name: Prefix
                        label: "IP Prefixes"
                        kind: SecurityPrefix
                        icon: "mdi:ip-network-outline"
                      - namespace: Security
                        name: IpamPrefix
                        label: "IPAM Prefixes"
                        kind: SecurityIpamPrefix
                        icon: "mdi:ip-network"
                      - namespace: Security
                        name: IPRange
                        label: "IP Ranges"
                        kind: SecurityIPRange
                        icon: "mdi:format-list-numbered"
                      - namespace: Security
                        name: FQDN
                        label: "Domain Names"
                        kind: SecurityFQDN
                        icon: "mdi:dns"
                      - namespace: Security
                        name: AddressGroup
                        label: "Address Groups"
                        kind: SecurityAddressGroup
                        icon: "mdi:folder"

                - namespace: Security
                  name: ServicesSubmenu
                  label: "Services & Applications"
                  icon: "mdi:application"
                  children:
                    data:
                      - namespace: Security
                        name: Service
                        label: "Network Services"
                        kind: SecurityService
                        icon: "mdi:application-outline"
                      - namespace: Security
                        name: ServiceRange
                        label: "Service Ranges"
                        kind: SecurityServiceRange
                        icon: "mdi:format-list-numbered"
                      - namespace: Security
                        name: ServiceGroup
                        label: "Service Groups"
                        kind: SecurityServiceGroup
                        icon: "mdi:folder-multiple"
                      - namespace: Security
                        name: Application
                        label: "Applications"
                        kind: SecurityApplication
                        icon: "mdi:application"

                - namespace: Security
                  name: WebSecurityMenu
                  label: "Web Security"
                  icon: "mdi:web"
                  children:
                    data:
                      - namespace: Security
                        name: URLCategory
                        label: "URL Categories"
                        kind: SecurityURLCategory
                        icon: "mdi:web"

    # ===================== DEVICE MANAGEMENT =====================
    - namespace: Dcim
      name: DeviceManagementMenu
      label: Device Management
      icon: "mdi:server"
      children:
        data:
          # --------- Core Infrastructure ---------
          - namespace: Dcim
            name: DevicesMenu
            label: "Infrastructure"
            icon: "mdi:server"
            children:
              data:
                - namespace: Dcim
                  name: GenericDevice
                  label: All Devices
                  kind: DcimGenericDevice
                  icon: "mdi:server"

                - name: Interface
                  namespace: Dcim
                  label: "Interfaces"
                  icon: "mdi:ethernet"
                  kind: DcimInterface

                - name: GenericSFP
                  namespace: Dcim
                  label: "SFP Modules"
                  icon: "mdi:expansion-card"
                  kind: DcimGenericSFP

          # --------- Network Management ---------
          - namespace: Network
            name: ServerMenu
            label: Network Services
            icon: "mdi:server-network"
            children:
              data:
                - namespace: Network
                  name: NTPServer
                  label: NTP Servers
                  kind: NetworkNTPServer
                  icon: "mdi:clock-outline"
                - namespace: Network
                  name: NameServer
                  label: DNS Servers
                  kind: NetworkNameServer
                  icon: "mdi:dns"

          # --------- Device Types & Platforms ---------
          - namespace: Dcim
            name: TypesMenu
            label: "Types & Platforms"
            icon: "mdi:cog"
            children:
              data:
                - namespace: Dcim
                  name: Platform
                  label: Platforms
                  kind: DcimPlatform
                  icon: "mdi:chip"

                - namespace: Dcim
                  name: DeviceType
                  label: Device Types
                  kind: DcimDeviceType
                  icon: "mdi:package-variant"

    # ===================== ROUTING =====================
    - namespace: Routing
      name: ManagementMenu
      label: Routing Management
      icon: "mdi:router"
      children:
        data:
          - namespace: Routing
            name: BGPMenu
            label: "BGP Management"
            icon: "mdi:router-network"
            children:
              data:
                - namespace: Routing
                  name: AutonomousSystem
                  label: "Autonomous Systems"
                  kind: RoutingAutonomousSystem
                  icon: "mdi:bank-circle-outline"

                - namespace: Routing
                  name: BGPPeerGroup
                  label: "BGP Peer Groups"
                  kind: RoutingBGPPeerGroup
                  icon: "mdi:view-grid-plus-outline"

                - namespace: Routing
                  name: BGPCommunity
                  label: "BGP Communities"
                  kind: RoutingBGPCommunity
                  icon: "mdi:tag-multiple"

          - namespace: Routing
            name: OSPFMenu
            label: "OSPF Management"
            icon: "mdi:network-outline"
            children:
              data:
                - namespace: Routing
                  name: OSPFArea
                  label: OSPF Areas
                  kind: RoutingOSPFArea
                  icon: "mdi:square-rounded-outline"

                - namespace: Routing
                  name: OSPFInterface
                  label: OSPF Interface Profiles
                  kind: RoutingOSPFInterface
                  icon: "mdi:shield-check"

          - namespace: Routing
            name: PIMMenu
            label: PIM Management
            icon: "mdi:pim-outline"
            children:
              data:
                - namespace: Routing
                  name: PIMInterface
                  label: PIM Interfaces
                  kind: RoutingPIMInterface
                  icon: "mdi:ethernet"

    # ===================== LOAD BALANCING =====================

    - namespace: Loadbalancing
      name: ManagementMenu
      label: LB Management
      icon: carbon:load-balancer-global
      children:
        data:
          - namespace: Loadbalancing
            name: VIP
            label: VIPs
            kind: LoadbalancerVIP
            icon: "carbon:floating-ip"
            description: "Virtual IPs (VIPs) used by the load balancer for routing traffic."
          - namespace: Loadbalancing
            name: HealthCheck
            label: Health-Checks
            kind: LoadbalancerHealthCheck
            icon: "tabler:checkup-list"
          - namespace: Loadbalancing
            name: Servers
            label: Backend Servers
            kind: LoadbalancerServer
            icon: mdi:server-plus